//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arquivos
    {
        public int ID { get; set; }
        public string Identificacao { get; set; }
        public Nullable<int> IDCNPJ { get; set; }
        public string NomeArquivo { get; set; }
        public string NumeroTAG { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
