//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoSenha2
    {
        public Nullable<int> Senha { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public int ID { get; set; }
        public string Filial { get; set; }
        public string Hora { get; set; }
        public string HoraChamada { get; set; }
        public string TempoTotal { get; set; }
    }
}
