//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanhoTosaDados
    {
        public int ID { get; set; }
        public Nullable<int> IDBanho { get; set; }
        public string DescricaoServico { get; set; }
        public Nullable<int> CodServico { get; set; }
        public Nullable<float> Quant { get; set; }
        public Nullable<decimal> ValorUnit { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Observacao { get; set; }
        public string Status { get; set; }
        public string Profissional { get; set; }
        public string Recepcionista { get; set; }
        public Nullable<System.DateTime> DataAgendamento { get; set; }
        public Nullable<System.DateTime> DataEnviado { get; set; }
        public Nullable<System.DateTime> DataTermino { get; set; }
        public string TemShampoo { get; set; }
        public string NomeShampoo { get; set; }
    }
}
