//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanhoTosa
    {
        public int ID { get; set; }
        public string Cliente { get; set; }
        public string Animal { get; set; }
        public string Tipo { get; set; }
        public string Obs { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> ValorDelivery { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Vendedor { get; set; }
        public string StatusFinanceiro { get; set; }
        public Nullable<decimal> ValorPago { get; set; }
        public string StatusServicos { get; set; }
        public string Observacoes { get; set; }
    }
}
