//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_usu
    {
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string NomeUsuario { get; set; }
        public string Tipo { get; set; }
        public string Ponto { get; set; }
        public string AlteraPonto { get; set; }
        public string RegraPonto { get; set; }
        public string Produtos { get; set; }
        public string AlteraSalvaEditaProd { get; set; }
        public string DeletaProd { get; set; }
        public string AcessoUsuarios { get; set; }
        public string InserirSalvarUsuario { get; set; }
        public string Deletarusuario { get; set; }
        public string Transportadoras { get; set; }
        public string InsSalvTransp { get; set; }
        public string DeletarTransp { get; set; }
        public string PalavraPasse { get; set; }
        public string OS { get; set; }
        public string InserirSalvarOS { get; set; }
        public string DeletarOS { get; set; }
        public string Funcionarios { get; set; }
        public string InserirSalvarFunc { get; set; }
        public string DeletarFunc { get; set; }
        public string Veiculos { get; set; }
        public string InserirSalvarVeiculos { get; set; }
        public string DeletarVeiculos { get; set; }
        public string PecasOS { get; set; }
        public string InserirSalvarPecasOS { get; set; }
        public string DeletarPecasOS { get; set; }
        public string ServicosOS { get; set; }
        public string InserirSalvarServicosOS { get; set; }
        public string DeletarServicosOS { get; set; }
        public string ClienteFornec { get; set; }
        public string InserirSalvarCliFornec { get; set; }
        public string deletarCliFornec { get; set; }
        public string HistoricoEstoque { get; set; }
        public string LancamentosEstoque { get; set; }
        public string InserirSalvarLancamentosEstoque { get; set; }
        public string NFE { get; set; }
        public string InserirSalvarNFE { get; set; }
        public string DeletarNFE { get; set; }
        public string RegistroTransp { get; set; }
        public string Tarifa { get; set; }
        public string InserirSalvarPagar { get; set; }
        public string InserirSalvarReceber { get; set; }
        public string InserirSalvarBanco { get; set; }
        public string InserirSalvarLancBancario { get; set; }
        public string DeletarPagar { get; set; }
        public string DeletarReceber { get; set; }
        public string DeletarBanco { get; set; }
        public string ContasPagar { get; set; }
        public string ContasReceber { get; set; }
        public string BaixarPgto { get; set; }
        public string BaixarReceb { get; set; }
        public string ConsultaPagar { get; set; }
        public string ConsultaReceb { get; set; }
        public string Bancos { get; set; }
        public string LancBancario { get; set; }
        public string Cheques { get; set; }
        public string Orcamento { get; set; }
        public string Vendas { get; set; }
        public string IndicesParcelas { get; set; }
        public string Balcao { get; set; }
        public string Atacado { get; set; }
        public string Vendedor { get; set; }
        public string Filial { get; set; }
        public string Estoque { get; set; }
        public string Caixa { get; set; }
        public string TipoOS { get; set; }
        public Nullable<decimal> DescontoPermitido { get; set; }
        public string PreVenda { get; set; }
        public string Conta { get; set; }
        public string Comissoes { get; set; }
        public string ComprasInicial { get; set; }
        public string Faturamento { get; set; }
        public string Estorno { get; set; }
        public string ExcluirLimpar { get; set; }
        public string AlterarPrecoProd { get; set; }
        public string LiberarLimite { get; set; }
        public string SolicitarLiberacao { get; set; }
        public string LiberarComercial { get; set; }
        public string LiberarFinanceiro { get; set; }
    }
}
