//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_OS_Online
    {
        public string Codigo { get; set; }
        public string Cliente { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataFinalizado { get; set; }
        public Nullable<float> ValorTotal { get; set; }
        public string DescricaoEquip { get; set; }
        public string Observacoes { get; set; }
        public string Descricao { get; set; }
        public string ProblemaEncontrado { get; set; }
        public Nullable<System.DateTime> DataConversao { get; set; }
        public Nullable<System.DateTime> PrevisaoAtendimento { get; set; }
        public Nullable<System.DateTime> DataTermino { get; set; }
        public string Tecnico { get; set; }
        public string HoraAtendimento { get; set; }
        public int Codigo2 { get; set; }
    }
}
