//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_Convenios
    {
        public int ID { get; set; }
        public string Cartao_convenio { get; set; }
        public string Administradora { get; set; }
        public string Contato { get; set; }
        public string Telefone { get; set; }
        public Nullable<float> Taxa { get; set; }
        public string DiaRecebimento { get; set; }
        public string Carencia { get; set; }
        public string TipoRede { get; set; }
    }
}
