//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_prod_anterior
    {
        public Nullable<int> Codigo { get; set; }
        public string Descricao { get; set; }
        public string CodFrabrica { get; set; }
        public string Marca { get; set; }
        public string ClassFiscal { get; set; }
        public string Endereco { get; set; }
        public Nullable<decimal> QtdEstoque { get; set; }
        public Nullable<float> Estmaximo { get; set; }
        public Nullable<float> EstMinimo { get; set; }
        public string ABC { get; set; }
        public string Aplicativo1 { get; set; }
        public string Aplicativo2 { get; set; }
        public string Aplicativo3 { get; set; }
        public string Aplicativo4 { get; set; }
        public string Aplicativo5 { get; set; }
        public Nullable<float> PrecoVendaAtacU { get; set; }
        public Nullable<decimal> PrecoVendaAtacR { get; set; }
        public Nullable<float> PrecoCustoU { get; set; }
        public Nullable<decimal> PrecoCustoR { get; set; }
        public Nullable<float> PrecoReposU { get; set; }
        public Nullable<decimal> PrecoReposR { get; set; }
        public string CodAp1 { get; set; }
        public string CodAp2 { get; set; }
        public string CodAp3 { get; set; }
        public string CodAp4 { get; set; }
        public string CodAp5 { get; set; }
        public Nullable<System.DateTime> DataPVenda { get; set; }
        public Nullable<System.DateTime> DataPCusto { get; set; }
        public Nullable<System.DateTime> DataPRepos { get; set; }
        public string UN { get; set; }
        public string apelido { get; set; }
        public string CodBarras { get; set; }
        public Nullable<float> PrecoVendaVarU { get; set; }
        public Nullable<decimal> PrecoVendaVarR { get; set; }
        public Nullable<float> PrecoVendaU { get; set; }
        public Nullable<decimal> PrecoVendaR { get; set; }
        public string SitTributaria { get; set; }
        public string observacao { get; set; }
        public string Pinagem { get; set; }
        public string TipoMemoria { get; set; }
        public string Sata { get; set; }
        public string IDE { get; set; }
        public string Frequencia { get; set; }
        public string DualCore { get; set; }
        public string FrequenciaBarramento { get; set; }
        public Nullable<float> ComissaoAtac { get; set; }
        public Nullable<float> ComissaoRepos { get; set; }
        public Nullable<float> ComissaoVar { get; set; }
        public Nullable<float> QtdAtacado { get; set; }
        public Nullable<float> PrecoAtacado { get; set; }
        public Nullable<float> PrecoAtacadoNormal { get; set; }
        public Nullable<float> PrecoAtac { get; set; }
        public Nullable<float> ICMS { get; set; }
        public string Fornec1 { get; set; }
        public Nullable<float> Fornec2 { get; set; }
        public Nullable<float> Fornec3 { get; set; }
        public Nullable<float> Fornec4 { get; set; }
        public Nullable<float> Fornec5 { get; set; }
        public Nullable<float> Fornec6 { get; set; }
        public Nullable<float> IPI { get; set; }
        public int Indice { get; set; }
        public Nullable<decimal> QuantFilial01 { get; set; }
        public Nullable<decimal> QuantFilial02 { get; set; }
        public Nullable<decimal> QuantFilial03 { get; set; }
        public Nullable<decimal> QuantFilial04 { get; set; }
        public Nullable<decimal> QuantFilial05 { get; set; }
        public Nullable<decimal> QuantFilial06 { get; set; }
        public Nullable<decimal> QuantFilial07 { get; set; }
        public Nullable<decimal> QuantFilial08 { get; set; }
        public Nullable<decimal> QuantFilial09 { get; set; }
        public Nullable<float> QuantFilial10 { get; set; }
        public Nullable<decimal> QuantCD { get; set; }
        public string Margem { get; set; }
        public string Grupo { get; set; }
        public Nullable<float> PesoBruto { get; set; }
        public string NCM { get; set; }
        public Nullable<float> PesoLiquido { get; set; }
        public string PrazoGarantia { get; set; }
        public Nullable<float> ISS { get; set; }
        public Nullable<decimal> Impostos { get; set; }
        public Nullable<decimal> Marketing { get; set; }
        public Nullable<decimal> DespesasFixas { get; set; }
        public byte[] Foto { get; set; }
        public string Link { get; set; }
        public Nullable<decimal> QTDVendido { get; set; }
        public string Status { get; set; }
        public string Somar { get; set; }
        public string CFOP { get; set; }
        public Nullable<decimal> PIS { get; set; }
        public Nullable<decimal> COFINS { get; set; }
        public Nullable<decimal> QtdPromo { get; set; }
        public string DataFinalPromo { get; set; }
        public string NCMentrada { get; set; }
        public string CFOPEntrada { get; set; }
        public string SitTributEntrada { get; set; }
        public Nullable<float> IPIEntrada { get; set; }
        public Nullable<float> ICMSEntrada { get; set; }
        public Nullable<float> ISSEntrada { get; set; }
        public Nullable<float> PISEntrada { get; set; }
        public Nullable<float> COFINSEntrada { get; set; }
        public string CSOSN { get; set; }
        public string TipoIPI { get; set; }
        public string TipoPIS { get; set; }
        public string TipoCOFINS { get; set; }
        public string CSOSNEntrada { get; set; }
        public string TipoIPIEntrada { get; set; }
        public string TipoPISEntrada { get; set; }
        public string TipoCOFINSEntrada { get; set; }
        public string ECF { get; set; }
        public string TipoComissao { get; set; }
    }
}
