//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_OS_Inform
    {
        public string Codigo { get; set; }
        public string Cliente { get; set; }
        public string Especie1 { get; set; }
        public string Motorista { get; set; }
        public string PlacaCavalo { get; set; }
        public string PlacaBitrem1 { get; set; }
        public string PlacaBitrem2 { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string KM { get; set; }
        public string Especie2 { get; set; }
        public string Especie3 { get; set; }
        public string Chassi1 { get; set; }
        public string Chassi2 { get; set; }
        public string Chassi3 { get; set; }
        public string Marca1 { get; set; }
        public string Marca2 { get; set; }
        public string Marca3 { get; set; }
        public string Cor1 { get; set; }
        public string Cor2 { get; set; }
        public string Cor3 { get; set; }
        public string ano1 { get; set; }
        public string ano2 { get; set; }
        public string ano3 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataFinalizado { get; set; }
        public Nullable<float> ValorTotal { get; set; }
        public string FoneCliente { get; set; }
        public string EnderecoCliente { get; set; }
        public string CidadeCliente { get; set; }
        public string TipoEquipamento { get; set; }
        public string DescricaoEquip { get; set; }
        public string NumSerieEquip { get; set; }
        public string Observacoes { get; set; }
        public string Contrato { get; set; }
        public string Descricao { get; set; }
        public string ProblemaEncontrado { get; set; }
        public Nullable<System.DateTime> DataAprovacao { get; set; }
        public Nullable<System.DateTime> PrevisaoEntrega { get; set; }
        public Nullable<System.DateTime> DataTermino { get; set; }
        public string Tecnico { get; set; }
        public string Tipo { get; set; }
        public string Modelo { get; set; }
        public string Placa { get; set; }
        public string Chassi { get; set; }
        public string Motor { get; set; }
        public string Cor { get; set; }
        public string Ano { get; set; }
        public string HoraAtendimento { get; set; }
        public int Codigo2 { get; set; }
        public string Prioridade { get; set; }
        public string NomeMotorista { get; set; }
        public string Entregue { get; set; }
        public string ObsEntrega { get; set; }
        public string Tecnico2 { get; set; }
        public string Tecnico3 { get; set; }
        public string Tecnico4 { get; set; }
        public string Tecnico5 { get; set; }
        public string Tecnico6 { get; set; }
        public string Projeto { get; set; }
        public string Pedido { get; set; }
        public string Documentacao { get; set; }
        public string Obra { get; set; }
        public string ResumoPecas { get; set; }
        public Nullable<decimal> ValorEstimado { get; set; }
        public string StatusFinanceiro { get; set; }
        public Nullable<decimal> ValorAberto { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Entradas { get; set; }
        public Nullable<decimal> Saidas { get; set; }
        public Nullable<decimal> EntradaRecebido { get; set; }
        public Nullable<decimal> TotalSaldo { get; set; }
        public Nullable<decimal> Desconto { get; set; }
    }
}
