//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_Func
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Apelido { get; set; }
        public string Cidade { get; set; }
        public string CEP { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Telefone { get; set; }
        public string Telefone2 { get; set; }
        public string InfFone { get; set; }
        public string Celular { get; set; }
        public string CelularTH { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string RG { get; set; }
        public string CPF_CNPJ { get; set; }
        public string CTPS { get; set; }
        public string PIS { get; set; }
        public string CatCNH { get; set; }
        public string CNH { get; set; }
        public Nullable<System.DateTime> ValCNH { get; set; }
        public string Cargo { get; set; }
        public string Pessoa { get; set; }
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        public Nullable<System.DateTime> DataInicioTrabalho { get; set; }
        public string NomePai { get; set; }
        public string NomeMae { get; set; }
        public string EstCivil { get; set; }
        public string TemDependentes { get; set; }
        public string Informdependetes { get; set; }
        public string Naturalidade { get; set; }
        public string Nacionalidade { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DataDemissao { get; set; }
        public string NomeBanco { get; set; }
        public string Agencia { get; set; }
        public string TipoConta { get; set; }
        public string Titular { get; set; }
        public string NumConta { get; set; }
        public string NumCartaoUnimed { get; set; }
        public Nullable<System.DateTime> InicioContratoUnimed { get; set; }
        public string TipoPlanoUnimed { get; set; }
        public string TemDepUnimed { get; set; }
        public string NomeDepUnimed { get; set; }
        public Nullable<float> Valor { get; set; }
        public string Conjuge { get; set; }
        public string CodigoBarras { get; set; }
        public string Horario { get; set; }
        public string Manha1 { get; set; }
        public string Manha2 { get; set; }
        public string Almoco1 { get; set; }
        public string Almoco2 { get; set; }
        public string Tarde1 { get; set; }
        public string Tarde2 { get; set; }
        public string Saida1 { get; set; }
        public string Saida2 { get; set; }
        public Nullable<float> Salario { get; set; }
        public string Senha { get; set; }
        public string Observacao { get; set; }
        public string Selecionado { get; set; }
        public Nullable<decimal> Comissao { get; set; }
        public string Email { get; set; }
    }
}
