//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_Veiculos
    {
        public string NumRegistro { get; set; }
        public string Veiculo { get; set; }
        public string EspecieTipo { get; set; }
        public string Placa { get; set; }
        public string Chassi { get; set; }
        public string Combustivel { get; set; }
        public string MarcaModelo { get; set; }
        public Nullable<int> AnoFab { get; set; }
        public Nullable<int> AnoMod { get; set; }
        public string CapPotCil { get; set; }
        public string Categoria { get; set; }
        public string Cor { get; set; }
        public string Proprietario { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string CPF_CNPJ { get; set; }
        public string Renavam { get; set; }
        public string Motorista { get; set; }
        public string Observacao { get; set; }
        public string Local { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public string Exercicio { get; set; }
        public Nullable<float> MediaVazio { get; set; }
        public Nullable<float> MediaCarregado { get; set; }
    }
}
