//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cad_OS
    {
        public string Codigo { get; set; }
        public string Cliente { get; set; }
        public string Especie1 { get; set; }
        public string Motorista { get; set; }
        public string PlacaCavalo { get; set; }
        public string PlacaBitrem1 { get; set; }
        public string PlacaBitrem2 { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string KM { get; set; }
        public string Especie2 { get; set; }
        public string Especie3 { get; set; }
        public string Chassi1 { get; set; }
        public string Chassi2 { get; set; }
        public string Chassi3 { get; set; }
        public string Marca1 { get; set; }
        public string Marca2 { get; set; }
        public string Marca3 { get; set; }
        public string Cor1 { get; set; }
        public string Cor2 { get; set; }
        public string Cor3 { get; set; }
        public string ano1 { get; set; }
        public string ano2 { get; set; }
        public string ano3 { get; set; }
        public int Codigo2 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataFinalizado { get; set; }
        public Nullable<float> ValorTotal { get; set; }
    }
}
