//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadAtacadoDados
    {
        public int Codigo { get; set; }
        public Nullable<int> CodigoItem { get; set; }
        public string Descricao { get; set; }
        public Nullable<float> Quant { get; set; }
        public Nullable<float> ValorUnit { get; set; }
        public string CodigoProduto { get; set; }
        public string Selecionado { get; set; }
        public string Grupo { get; set; }
        public string Tipo { get; set; }
    }
}
