//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadAnimais
    {
        public int ID { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public string Nome { get; set; }
        public string Raca { get; set; }
        public string CorPelo { get; set; }
        public string Porte { get; set; }
        public string Apelido { get; set; }
        public string Especie { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string Sexo { get; set; }
        public string Status { get; set; }
        public string Pacote { get; set; }
    }
}
