//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadAtacado
    {
        public string Descricao { get; set; }
        public Nullable<float> Quantidade { get; set; }
        public Nullable<float> Estmaximo { get; set; }
        public Nullable<float> EstMinimo { get; set; }
        public Nullable<float> PrecoVendaAtacR { get; set; }
        public Nullable<float> PrecoCustoR { get; set; }
        public string UN { get; set; }
        public string apelido { get; set; }
        public string CodBarras { get; set; }
        public Nullable<float> PrecoVendaVarR { get; set; }
        public string TipoMemoria { get; set; }
        public string Sata { get; set; }
        public string IDE { get; set; }
        public Nullable<float> Comissao { get; set; }
        public int Codigo { get; set; }
    }
}
