//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadServicoOS_Inform
    {
        public string OS { get; set; }
        public string Solicitado { get; set; }
        public string Executado { get; set; }
        public Nullable<float> Valor { get; set; }
        public string Somado { get; set; }
        public string UN { get; set; }
        public Nullable<double> Quant { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> CodPeca { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> Comissao { get; set; }
    }
}
