//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campo
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Hectares { get; set; }
        public Nullable<System.DateTime> DataPlantio { get; set; }
        public Nullable<System.DateTime> DataColheita { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string NomeFazenda { get; set; }
        public string IPR { get; set; }
        public string Campo1 { get; set; }
        public string Safra { get; set; }
        public string Germinacao { get; set; }
        public string Peneira { get; set; }
        public string Boletim { get; set; }
        public string Termo { get; set; }
        public string Vigor { get; set; }
        public string Area { get; set; }
        public Nullable<System.DateTime> DataBeneficiamento { get; set; }
        public Nullable<decimal> QtdAnalisado { get; set; }
        public Nullable<decimal> ScAnalisaco { get; set; }
        public Nullable<decimal> QtdSacas { get; set; }
        public Nullable<decimal> PesoSacas { get; set; }
        public string ProdutoVinculado { get; set; }
        public string Produtor { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> IDProdutoVinculado { get; set; }
    }
}
