//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartoesVenda
    {
        public int ID { get; set; }
        public string NumCartao { get; set; }
        public string Bandeira { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public Nullable<int> IDPgto { get; set; }
        public string NomeCartao { get; set; }
        public Nullable<System.DateTime> Validade { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> NumVenda { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> ValorReal { get; set; }
        public Nullable<decimal> Diferenca { get; set; }
        public string Selecionado { get; set; }
        public string Status { get; set; }
    }
}
