//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        public int ID { get; set; }
        public string Numero { get; set; }
        public string Banco { get; set; }
        public string Conta { get; set; }
        public string Validade { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public string Nome { get; set; }
        public string Bandeira { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> DiaInicio { get; set; }
        public Nullable<System.DateTime> DiaFim { get; set; }
        public Nullable<decimal> ValorExtra { get; set; }
    }
}
