//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFOP_OPERACAO
    {
        public int COD_CFOP_OPERACAO { get; set; }
        public string DESC_OPERACAO { get; set; }
        public Nullable<int> COD_CFOP_GRUPO { get; set; }
    }
}
