//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFOP_CODIGO
    {
        public int COD_CFOP_CODIGO { get; set; }
        public string DESC_OPERACAO { get; set; }
        public Nullable<int> ICMS { get; set; }
        public Nullable<int> ISS { get; set; }
        public Nullable<int> IPI { get; set; }
        public Nullable<int> DEVOLUCAO { get; set; }
        public string TIPONOTA { get; set; }
        public Nullable<int> DENTRO_ESTADO { get; set; }
        public Nullable<int> SAIDA_ESTOQUE { get; set; }
        public Nullable<int> ENTRADA_ESTOQUE { get; set; }
        public Nullable<int> NENHUM { get; set; }
        public Nullable<int> VENDA { get; set; }
        public string TIPO { get; set; }
        public string DADOS_ADICIONAIS { get; set; }
        public string OBS { get; set; }
        public Nullable<int> COD_CFOP_OPERACAO { get; set; }
        public Nullable<int> COD_CFOP_GRUPO { get; set; }
    }
}
