//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidades
    {
        public string Cidade { get; set; }
        public string UF { get; set; }
        public int ID { get; set; }
        public string Descricao { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public Nullable<int> Codigo { get; set; }
    }
}
