//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cli_Fornec2
    {
        public Nullable<int> Codigo { get; set; }
        public string Nome { get; set; }
        public string RazaoSocial { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string RG { get; set; }
        public string CPF_CNPJ { get; set; }
        public string Pessoa { get; set; }
        public string CEP { get; set; }
        public string Fone1 { get; set; }
        public string Fone2 { get; set; }
        public string Celular { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Status { get; set; }
        public string RG_InscEst { get; set; }
        public string UF { get; set; }
        public string Tipo { get; set; }
        public string Bairro { get; set; }
        public string Fax { get; set; }
        public string Site { get; set; }
        public string Contrato { get; set; }
        public string Email { get; set; }
        public string TemComputador { get; set; }
        public string QuemAtende { get; set; }
        public string PretendeMudar { get; set; }
        public string InteressePromocoes { get; set; }
        public string Abertura { get; set; }
        public string Observacao { get; set; }
        public Nullable<float> Credito { get; set; }
        public Nullable<int> PeriodoCredito { get; set; }
        public string NomeTratamento { get; set; }
        public string Estrategia { get; set; }
        public string Classificacao { get; set; }
        public string E_mail { get; set; }
        public int ID { get; set; }
        public string EstadoCivil { get; set; }
        public string Filiacao { get; set; }
        public string Residencia { get; set; }
        public string TempoResidencia { get; set; }
        public string CasaPropria { get; set; }
        public Nullable<float> ValorAluguel { get; set; }
        public string ResidenciaAnterior { get; set; }
        public string CidadeResidenciaAnterior { get; set; }
        public string LocalTrabalho { get; set; }
        public string Funcao { get; set; }
        public string Natural { get; set; }
        public string EnderecoTrabalho { get; set; }
        public string CidadeTrabalho { get; set; }
        public string FoneTrabalho { get; set; }
        public Nullable<System.DateTime> DataAdmissao { get; set; }
        public Nullable<float> Salario { get; set; }
        public string TipoFamiliar { get; set; }
        public string EstCivilFamiliar { get; set; }
        public Nullable<System.DateTime> DataNascFamiliar { get; set; }
        public string LocalNascFamiliar { get; set; }
        public string RGFamiliar { get; set; }
        public string CPFFamiliar { get; set; }
        public string FiliacaoFamiliar { get; set; }
        public string ResidenciaFamiliar { get; set; }
        public string FoneFamiliar { get; set; }
        public string CidadeFamiliar { get; set; }
        public string CasaPropriaFamiliar { get; set; }
        public string TempoResidenciaFamiliar { get; set; }
        public Nullable<float> ValorAluguelFamiliar { get; set; }
        public Nullable<float> PensaoFamiliar { get; set; }
        public Nullable<System.DateTime> DataExpedicao { get; set; }
        public string LocalTrabalhoFamiliar { get; set; }
        public string FuncaoFamiliar { get; set; }
        public string EnderecoTrabalhoFamiliar { get; set; }
        public string CidadeTrabalhoFamiliar { get; set; }
        public Nullable<float> SalarioFamiliar { get; set; }
        public string InscMunicipal { get; set; }
        public string PlanoPgto { get; set; }
        public string BensCliente { get; set; }
        public string RefBancaria { get; set; }
        public string Avalista { get; set; }
        public string Transportadora { get; set; }
        public string Alerta { get; set; }
        public string FoneAvalista { get; set; }
        public string RamoAtividade { get; set; }
        public string Representante { get; set; }
        public string Produtos { get; set; }
        public string FoneTrabFamiliar { get; set; }
        public Nullable<int> Pontos { get; set; }
        public string Placa { get; set; }
        public string Time { get; set; }
    }
}
