//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comandos
    {
        public int ID { get; set; }
        public string Comando { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> Ordenacao { get; set; }
    }
}
