//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comissao
    {
        public string Descricao { get; set; }
        public Nullable<float> Valor { get; set; }
        public string Indice { get; set; }
        public Nullable<float> Comissao1 { get; set; }
        public Nullable<float> Venda { get; set; }
        public int Codigo { get; set; }
        public string Tipo { get; set; }
        public string NumVenda { get; set; }
    }
}
