//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public Nullable<int> CodigoCompra { get; set; }
        public string CodigoProduto { get; set; }
        public string Descricao { get; set; }
        public Nullable<float> Quant { get; set; }
        public Nullable<float> ValorUnit { get; set; }
        public Nullable<float> ValorTotal { get; set; }
        public string SitTribut { get; set; }
        public Nullable<float> IPI { get; set; }
        public string ClassFiscal { get; set; }
        public string Estoque { get; set; }
        public string Local { get; set; }
        public int CodigoItem { get; set; }
        public string Fornecedor { get; set; }
        public string CodigoFornec { get; set; }
        public string Entregue { get; set; }
    }
}
