//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignacao
    {
        public int ID { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public string Status { get; set; }
        public Nullable<int> NumAcerto { get; set; }
        public string TabelaPreco { get; set; }
        public string Vendedor { get; set; }
        public string NFE { get; set; }
    }
}
