//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContaGrafica
    {
        public int ID { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> ICMSSaida { get; set; }
        public Nullable<decimal> ICMSSubstSaida { get; set; }
        public Nullable<decimal> IPISaida { get; set; }
        public Nullable<decimal> PISSaida { get; set; }
        public Nullable<decimal> COFINSSaida { get; set; }
        public Nullable<decimal> ICMSEntrada { get; set; }
        public Nullable<decimal> ICMSSubstEntrada { get; set; }
        public Nullable<decimal> IPIEntrada { get; set; }
        public Nullable<decimal> PISEntrada { get; set; }
        public Nullable<decimal> COFINSEntrada { get; set; }
        public Nullable<decimal> TotaisEntrada { get; set; }
        public Nullable<decimal> TotaisSaida { get; set; }
        public Nullable<decimal> Diferenca { get; set; }
    }
}
