//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contatos
    {
        public int ID { get; set; }
        public string Tratamento { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Empresa { get; set; }
        public string Cargo { get; set; }
        public string Email { get; set; }
        public string EnderecoWEB { get; set; }
        public string FoneComercial { get; set; }
        public string FoneResidencial { get; set; }
        public string FoneCelular { get; set; }
        public string Fax { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string CEP { get; set; }
        public string Pais { get; set; }
        public string Obs { get; set; }
        public string Grupo { get; set; }
        public string Foto { get; set; }
    }
}
