//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContasPagar
    {
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataConta { get; set; }
        public string PlanoContas { get; set; }
        public string Fornecedor { get; set; }
        public string NumDocumento { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<float> JurosDiarios { get; set; }
        public Nullable<float> Valor { get; set; }
        public Nullable<float> Desconto { get; set; }
        public Nullable<float> Multa { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public string Portador { get; set; }
        public string Status { get; set; }
        public Nullable<int> Parcelas { get; set; }
        public string Observacao { get; set; }
        public string Pendencias { get; set; }
        public string FormaPgto { get; set; }
        public Nullable<System.DateTime> DataPgto { get; set; }
        public string Banco { get; set; }
        public string Conta { get; set; }
        public string Estilo { get; set; }
        public Nullable<float> ValorCorrigido { get; set; }
        public Nullable<int> Codigo { get; set; }
        public string ChegouBoleto { get; set; }
        public string BaixaMultipla { get; set; }
        public string Filial { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> ValorOriginal { get; set; }
        public int ID { get; set; }
    }
}
