//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControleCaixa
    {
        public int ID { get; set; }
        public string Loja { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Responsavel { get; set; }
        public string PDV { get; set; }
        public string Troco { get; set; }
        public string Brindes { get; set; }
        public string Garcia { get; set; }
        public string Zacarias { get; set; }
        public string MgaFM { get; set; }
        public string Boleto { get; set; }
        public string Gelo { get; set; }
        public string Acougue { get; set; }
        public string Passe { get; set; }
        public string Cancelado { get; set; }
        public string Dinheiro { get; set; }
        public string Moeda { get; set; }
        public string MasterCredito { get; set; }
        public string MasterDebito { get; set; }
        public string VisaCredito { get; set; }
        public string VisaDebito { get; set; }
        public string Hipercard { get; set; }
        public string Outros { get; set; }
        public string Total { get; set; }
        public string Diferenca { get; set; }
        public string TotalVenda { get; set; }
    }
}
