//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContasReceberNFE
    {
        public Nullable<int> Codigo { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataConta { get; set; }
        public string PlanoContas { get; set; }
        public string Cliente { get; set; }
        public string NumDocumento { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<float> JurosDiarios { get; set; }
        public Nullable<float> Valor { get; set; }
        public Nullable<float> Desconto { get; set; }
        public Nullable<float> Multa { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public string Portador { get; set; }
        public string Status { get; set; }
        public string Parcelas { get; set; }
        public string Observacao { get; set; }
        public string Pendencias { get; set; }
        public string FormaPgto { get; set; }
        public Nullable<System.DateTime> DataRecebimento { get; set; }
        public string Banco { get; set; }
        public string Conta { get; set; }
        public string Estilo { get; set; }
        public Nullable<float> ValorFatura { get; set; }
        public string TotalParcelas { get; set; }
        public string BaixaMultipla { get; set; }
        public string Extenso { get; set; }
        public string Praca { get; set; }
        public string Filial { get; set; }
        public Nullable<int> CodCli { get; set; }
        public string EmitenteCheque { get; set; }
        public string NumCheque { get; set; }
        public string CNPJCPFCheque { get; set; }
        public Nullable<System.DateTime> EmissaoCheque { get; set; }
        public Nullable<System.DateTime> VencimentoCheque { get; set; }
        public string BancoCheque { get; set; }
        public string ContaCheque { get; set; }
        public string AgenciaCheque { get; set; }
        public string LinhaDigitavel { get; set; }
        public Nullable<decimal> ValorDescontoDuplicata { get; set; }
        public Nullable<decimal> ValorDesconto { get; set; }
        public Nullable<decimal> JurosTotais { get; set; }
        public string NumNFE { get; set; }
        public string JurosManuais { get; set; }
        public string StatusCheque { get; set; }
        public Nullable<decimal> ValorRecebido { get; set; }
        public int ID { get; set; }
    }
}
