//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurvaPeriodo
    {
        public int ID { get; set; }
        public string MesAno { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> ContasRecebidas { get; set; }
        public Nullable<decimal> ContasPagas { get; set; }
        public Nullable<decimal> TotalCMV { get; set; }
        public Nullable<decimal> TotalOutasDespesas { get; set; }
        public Nullable<decimal> TotalNFEntrada { get; set; }
    }
}
