//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurvaMes
    {
        public int ID { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> C01 { get; set; }
        public Nullable<decimal> C02 { get; set; }
        public Nullable<decimal> C03 { get; set; }
        public Nullable<decimal> C04 { get; set; }
        public Nullable<decimal> C05 { get; set; }
        public Nullable<decimal> C06 { get; set; }
        public Nullable<decimal> C07 { get; set; }
        public Nullable<decimal> C08 { get; set; }
        public Nullable<decimal> C09 { get; set; }
        public Nullable<decimal> C10 { get; set; }
        public Nullable<decimal> C11 { get; set; }
        public Nullable<decimal> C12 { get; set; }
        public Nullable<decimal> C13 { get; set; }
        public Nullable<decimal> C14 { get; set; }
        public Nullable<decimal> C15 { get; set; }
        public Nullable<decimal> C16 { get; set; }
        public Nullable<decimal> C17 { get; set; }
        public Nullable<decimal> C18 { get; set; }
        public Nullable<decimal> C19 { get; set; }
        public Nullable<decimal> C20 { get; set; }
        public Nullable<decimal> C21 { get; set; }
        public Nullable<decimal> C22 { get; set; }
        public Nullable<decimal> C23 { get; set; }
        public Nullable<decimal> C24 { get; set; }
        public Nullable<decimal> C25 { get; set; }
        public Nullable<decimal> C26 { get; set; }
        public Nullable<decimal> C27 { get; set; }
        public Nullable<decimal> C28 { get; set; }
        public Nullable<decimal> C29 { get; set; }
        public Nullable<decimal> C30 { get; set; }
        public Nullable<decimal> C31 { get; set; }
    }
}
