//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxSchedulerResourcesTable
    {
        public int ResourceID { get; set; }
        public Nullable<int> ResourceColor { get; set; }
        public string ResourceName { get; set; }
        public Nullable<int> ResourceImageIndex { get; set; }
        public string Inicio { get; set; }
        public string Fim { get; set; }
    }
}
