//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxSchedulerTable
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public Nullable<int> Options { get; set; }
        public string Caption { get; set; }
        public Nullable<int> RecurrenceIndex { get; set; }
        public string Location { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public Nullable<int> ReminderMinutes { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> LabelColor { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<System.DateTime> ActualFinish { get; set; }
        public string SyncIDField { get; set; }
        public byte[] ResourceID { get; set; }
        public byte[] RecurrenceInfo { get; set; }
    }
}
