//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosNFE
    {
        public string NumeroNF { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public Nullable<float> DescontoCento { get; set; }
        public Nullable<float> Desconto { get; set; }
        public string SitTributaria { get; set; }
        public Nullable<float> IPI { get; set; }
        public string Unidade { get; set; }
        public Nullable<float> Quant { get; set; }
        public Nullable<float> ValorUnitario { get; set; }
        public Nullable<float> ValorTotal { get; set; }
        public Nullable<float> ICMS { get; set; }
        public Nullable<float> ValorIPI { get; set; }
        public string ClassFiscal { get; set; }
        public string Codificado { get; set; }
        public string Estoque { get; set; }
        public string CFOP { get; set; }
        public string DescricaoCFOP { get; set; }
        public Nullable<System.DateTime> Validade { get; set; }
        public string NCM { get; set; }
        public int ID { get; set; }
        public string CodigoEAN { get; set; }
    }
}
