//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosCotacao
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public string Un { get; set; }
        public Nullable<decimal> QtdTotal { get; set; }
        public Nullable<decimal> ValorAnterior { get; set; }
        public string Fornec1 { get; set; }
        public string Fornec2 { get; set; }
        public string Fornec3 { get; set; }
        public string Fornec4 { get; set; }
        public string FornecMenor { get; set; }
        public Nullable<decimal> Unitf1 { get; set; }
        public Nullable<decimal> UnitF2 { get; set; }
        public Nullable<decimal> UnitF3 { get; set; }
        public Nullable<decimal> UnitF4 { get; set; }
        public Nullable<decimal> UnitMenor { get; set; }
        public Nullable<decimal> TotalF1 { get; set; }
        public Nullable<decimal> TotalF2 { get; set; }
        public Nullable<decimal> TotalF3 { get; set; }
        public Nullable<decimal> TotalF4 { get; set; }
        public Nullable<decimal> TotalMenor { get; set; }
        public string NumCotacao { get; set; }
        public string Fornec5 { get; set; }
        public string Fornec6 { get; set; }
        public Nullable<decimal> PrecoPrevisto { get; set; }
        public Nullable<decimal> UnitF5 { get; set; }
        public Nullable<decimal> UnitF6 { get; set; }
        public Nullable<decimal> TotalF5 { get; set; }
        public Nullable<decimal> TotalF6 { get; set; }
        public Nullable<decimal> Desvio { get; set; }
    }
}
