//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosBoletim
    {
        public int ID { get; set; }
        public string Boletim { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Especificacao { get; set; }
        public string Numero { get; set; }
        public string Fornecedor { get; set; }
        public string CodigoObra { get; set; }
        public string Obra { get; set; }
        public string PlanoContas { get; set; }
        public string Estilo { get; set; }
        public string Local { get; set; }
        public Nullable<float> Valor { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public string Especie { get; set; }
        public string Descricao { get; set; }
    }
}
