//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosSoLicitacao
    {
        public int ID { get; set; }
        public Nullable<int> NumSO { get; set; }
        public string Descricao { get; set; }
        public string Un { get; set; }
        public Nullable<decimal> Qtd { get; set; }
        public string Obs { get; set; }
        public string Selecionado { get; set; }
        public string CodProduto { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public Nullable<decimal> TotalUnit { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<decimal> TotalGeral { get; set; }
        public string Cor { get; set; }
        public Nullable<decimal> Gramat { get; set; }
    }
}
