//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosNotasNSU
    {
        public int ID { get; set; }
        public Nullable<int> IDNSU { get; set; }
        public string Descricao { get; set; }
        public string Qtd { get; set; }
        public string UnCom { get; set; }
        public string ValorUnit { get; set; }
        public string ValorTotal { get; set; }
        public string CodigoProduto { get; set; }
        public string NCM { get; set; }
        public string CEST { get; set; }
        public string IndEscRelevante { get; set; }
        public string CNPJFabricante { get; set; }
        public string CodBenef { get; set; }
        public string EXTIPI { get; set; }
        public string CFOP { get; set; }
        public string OutrasDesp { get; set; }
        public string Desconto { get; set; }
        public string ValSeguro { get; set; }
        public string ValFrete { get; set; }
        public string IndicadorComposicaoNFE { get; set; }
        public string EANGtinComercial { get; set; }
        public string EANGtinTributavel { get; set; }
        public string UnTrib { get; set; }
        public string QtdTrib { get; set; }
        public string ValUnitCom { get; set; }
        public string ValUnitTrib { get; set; }
        public string PedidoCompra { get; set; }
        public string ItemPedidoCompra { get; set; }
        public string ValTributos { get; set; }
        public string NumFichaCompensaImport { get; set; }
        public string OrigemMercadoria { get; set; }
        public string TributICMS { get; set; }
        public string ModalidadeOperacao { get; set; }
        public string ReducaoBC { get; set; }
        public string ValorBCICMS { get; set; }
        public string AliquotaICMS { get; set; }
        public string ValorICMS { get; set; }
        public string ValorICMSOperacao { get; set; }
        public string PercentualDiferimento { get; set; }
        public string ICMSDiferido { get; set; }
        public string BaseFCP { get; set; }
        public string PercentualFCP { get; set; }
        public string ValorFCP { get; set; }
        public string ClasseEnqIPI { get; set; }
        public string CodigoEnqIPI { get; set; }
        public string CodSelo { get; set; }
        public string CNPJProdutor { get; set; }
        public string QtdSelos { get; set; }
        public string CSTIPI { get; set; }
        public string QtdUnidadePadrao { get; set; }
        public string ValorUnidade { get; set; }
        public string ValorIPI { get; set; }
        public string BaseCalculoIPI { get; set; }
        public string AliquotaIPI { get; set; }
        public string CSTPIS { get; set; }
        public string BaseCalculoPIS { get; set; }
        public string AliquotaPIS { get; set; }
        public string ValorPIS { get; set; }
        public string CSTCOFINS { get; set; }
        public string BaseCalculoCOFINS { get; set; }
        public string AliquotaCOFINS { get; set; }
        public string ValorCOFINS { get; set; }
    }
}
