//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desempenho
    {
        public int Codigo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<float> Estoque { get; set; }
        public Nullable<float> APagar { get; set; }
        public Nullable<float> AReceber { get; set; }
        public Nullable<float> Resultado { get; set; }
        public Nullable<float> Bancos { get; set; }
    }
}
