//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public string Nome { get; set; }
        public string RazaoSocial { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string CNPJ { get; set; }
        public string Fone1 { get; set; }
        public string Fone2 { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Status { get; set; }
        public string InscEst { get; set; }
        public string UF { get; set; }
        public int Codigo { get; set; }
        public byte[] Foto { get; set; }
        public string Responsavel { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public string CRT { get; set; }
        public string ECF { get; set; }
        public string MensagemECF { get; set; }
        public string Site { get; set; }
        public string Email { get; set; }
        public Nullable<int> CodCidade { get; set; }
        public string Certificado { get; set; }
        public string SenhaCertificado { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public string CSOSN { get; set; }
        public string TipoPIS { get; set; }
        public string TipoIPI { get; set; }
        public string TipoCOFINS { get; set; }
        public string CSC { get; set; }
        public string Registro { get; set; }
        public string IE { get; set; }
        public string DocumentoResponsavel { get; set; }
        public string TipoDocumentoResp { get; set; }
        public string Login { get; set; }
        public Nullable<int> ID { get; set; }
        public string Renasem { get; set; }
        public string NomeRespTecnico { get; set; }
        public string CREARespTecnico { get; set; }
        public string CPFRespTecnico { get; set; }
        public string FoneRespTecnico { get; set; }
        public string CidadeRespTecnico { get; set; }
        public string EnderecoRespTecnico { get; set; }
        public string RENASEMRespTecnico { get; set; }
    }
}
