//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresasClientes
    {
        public string Nome { get; set; }
        public string RazaoSocial { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string CNPJ { get; set; }
        public string Fone1 { get; set; }
        public string Fone2 { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Status { get; set; }
        public string InscEst { get; set; }
        public string UF { get; set; }
        public int ID { get; set; }
        public string Responsavel { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public string CRT { get; set; }
        public string Email { get; set; }
        public Nullable<int> CodCidade { get; set; }
        public string Certificado { get; set; }
        public string SenhaCertificado { get; set; }
        public string CSOSN { get; set; }
        public string TipoPIS { get; set; }
        public string TipoIPI { get; set; }
        public string TipoCOFINS { get; set; }
        public string CSC { get; set; }
        public string Registro { get; set; }
        public Nullable<int> IDEmpresa { get; set; }
        public string UltimaNSU { get; set; }
    }
}
