//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipEmpresa
    {
        public string Descricao { get; set; }
        public string CodBarras { get; set; }
        public Nullable<System.DateTime> Validade { get; set; }
        public string Status { get; set; }
        public string Local { get; set; }
        public string Obs { get; set; }
        public string CodVenda { get; set; }
        public int ID { get; set; }
        public string Modelo { get; set; }
        public Nullable<System.DateTime> DataIndicacao { get; set; }
        public Nullable<int> QtdReal { get; set; }
        public string Sabor { get; set; }
        public string LocalEstoque { get; set; }
    }
}
