//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturFran
    {
        public int ID { get; set; }
        public string Franquia { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<int> Posicao { get; set; }
        public Nullable<int> PosicaoAnterior { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
