//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FechamentoCaixa
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string FormaPGTO { get; set; }
        public Nullable<decimal> Digitado { get; set; }
        public Nullable<decimal> Sistema { get; set; }
        public Nullable<decimal> Diferenca { get; set; }
        public Nullable<decimal> TotalDigitado { get; set; }
        public Nullable<decimal> TotalSistema { get; set; }
        public Nullable<decimal> TotalDiferenca { get; set; }
        public string Operador { get; set; }
        public string Tipo { get; set; }
    }
}
