//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FechaHVet
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> DataAtendimento { get; set; }
        public Nullable<System.DateTime> DataBaixa { get; set; }
        public Nullable<int> IDVet { get; set; }
        public string Veterinario { get; set; }
        public string NomeAnimal { get; set; }
        public string Telefone { get; set; }
        public Nullable<decimal> TotalClinica { get; set; }
        public Nullable<decimal> Consultas { get; set; }
        public Nullable<decimal> DiariasInternamento { get; set; }
        public Nullable<decimal> Exames { get; set; }
        public Nullable<decimal> Externo { get; set; }
        public Nullable<decimal> Aplicacoes { get; set; }
        public Nullable<decimal> Ultrassom { get; set; }
        public Nullable<decimal> RaioX { get; set; }
        public Nullable<decimal> Materiais { get; set; }
        public Nullable<decimal> Anestesista1 { get; set; }
        public Nullable<decimal> Anestesista2 { get; set; }
        public Nullable<decimal> Anestesista3 { get; set; }
        public Nullable<decimal> Anestesista4 { get; set; }
        public Nullable<decimal> Anestesista5 { get; set; }
        public Nullable<decimal> Anestesista6 { get; set; }
        public Nullable<decimal> Anestesista7 { get; set; }
        public Nullable<decimal> Cirurgia { get; set; }
        public Nullable<decimal> Fluidoterapia { get; set; }
        public Nullable<decimal> Outros { get; set; }
        public Nullable<decimal> DepositoInicial { get; set; }
        public Nullable<decimal> TotalVacinas { get; set; }
        public Nullable<decimal> VacinaVirose { get; set; }
        public Nullable<decimal> VacinaPro { get; set; }
        public Nullable<decimal> VacinaGripe { get; set; }
        public Nullable<decimal> VacinaRaiva { get; set; }
        public Nullable<decimal> TotalEstetica { get; set; }
        public Nullable<decimal> BanhoTosa { get; set; }
        public Nullable<decimal> CorteUnha { get; set; }
        public Nullable<decimal> OutrosEstetica { get; set; }
        public Nullable<decimal> TotalDiversos { get; set; }
        public Nullable<decimal> Hotel { get; set; }
        public Nullable<decimal> KM { get; set; }
        public Nullable<decimal> OutrosDiversos { get; set; }
        public Nullable<decimal> PetShop { get; set; }
        public Nullable<decimal> Descontos { get; set; }
        public Nullable<decimal> Juros { get; set; }
        public string FormaPGTO { get; set; }
        public Nullable<decimal> TotalGeral { get; set; }
    }
}
