//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ferramentas
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public Nullable<float> Qtd { get; set; }
        public string Local { get; set; }
        public string Endereco { get; set; }
        public Nullable<int> IDReserva { get; set; }
        public Nullable<System.DateTime> DataUltimaLiberacao { get; set; }
    }
}
