//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluxoSemana
    {
        public int ID { get; set; }
        public string Semana { get; set; }
        public Nullable<float> CRSaldoAnterior { get; set; }
        public Nullable<float> CRFaturamentoDia { get; set; }
        public Nullable<float> CRCheques { get; set; }
        public Nullable<float> CRSaldo { get; set; }
        public Nullable<float> CPSaldoAnterior { get; set; }
        public Nullable<float> CPDia { get; set; }
        public Nullable<float> CPSaldo { get; set; }
        public Nullable<float> SaldoSemana { get; set; }
        public Nullable<float> SaldoFluxo { get; set; }
    }
}
