//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluxoCaixa
    {
        public int ID { get; set; }
        public Nullable<float> CRSaldoAnterior { get; set; }
        public Nullable<float> CRFaturamentoDia { get; set; }
        public Nullable<float> CRSaldo { get; set; }
        public string ContasSemana { get; set; }
        public Nullable<float> CRSaldoAnteriorSemana { get; set; }
        public Nullable<float> CRChequesReceber { get; set; }
        public Nullable<float> CRSaldoSemana { get; set; }
        public Nullable<float> CPSaldoAnterior { get; set; }
        public Nullable<float> CPDia { get; set; }
        public Nullable<float> CPSaldoAtual { get; set; }
        public Nullable<float> CPSaldoAnteriorSemana { get; set; }
        public Nullable<float> CPPagar { get; set; }
        public Nullable<float> CPSaldoSemana { get; set; }
        public Nullable<float> SaldoSemana { get; set; }
        public Nullable<float> DuplicataReceber { get; set; }
        public Nullable<float> ChequesReceberDevolvidos { get; set; }
        public Nullable<float> Comissoes { get; set; }
        public Nullable<float> DescontosConcedidos { get; set; }
        public Nullable<float> JurosPagos { get; set; }
        public Nullable<float> DuplicatasDescontadas { get; set; }
        public Nullable<float> DuplicatasPagar { get; set; }
        public Nullable<float> TotalRecebidoDia { get; set; }
        public Nullable<float> TotalPagoDia { get; set; }
    }
}
