//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folha
    {
        public int ID { get; set; }
        public string Funcionario { get; set; }
        public Nullable<float> ValeTransporte { get; set; }
        public Nullable<float> INSS { get; set; }
        public Nullable<float> Antecipacao { get; set; }
        public Nullable<float> Comissao { get; set; }
        public Nullable<float> Outros { get; set; }
        public Nullable<float> Total { get; set; }
        public string Periodo { get; set; }
        public Nullable<float> Salario { get; set; }
    }
}
