//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public string Itens { get; set; }
        public string Link { get; set; }
        public byte[] Foto { get; set; }
        public string Imprimir { get; set; }
        public string Imprimir2 { get; set; }
        public Nullable<decimal> Comissao { get; set; }
        public string Imprimir3 { get; set; }
        public string Especial { get; set; }
        public string Imprimir4 { get; set; }
        public string NCM { get; set; }
        public string CEST { get; set; }
        public string CFOP { get; set; }
        public string CFOPInter { get; set; }
        public string CSOSN { get; set; }
        public string CSOSNST { get; set; }
    }
}
