//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impresso
    {
        public int ID { get; set; }
        public string Linha1 { get; set; }
        public string Linha2 { get; set; }
        public string Linha3 { get; set; }
        public string Linha4 { get; set; }
        public string Linha5 { get; set; }
        public string Linha6 { get; set; }
        public string Linha7 { get; set; }
        public string Linha8 { get; set; }
        public string Linha9 { get; set; }
        public string Linha10 { get; set; }
        public string Linha11 { get; set; }
        public string Linha12 { get; set; }
        public string Linha13 { get; set; }
        public string Linha14 { get; set; }
        public string Linha15 { get; set; }
        public string Linha16 { get; set; }
        public string Linha17 { get; set; }
    }
}
