//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformComplementares
    {
        public int ID { get; set; }
        public Nullable<int> CodigoCliente { get; set; }
        public Nullable<System.DateTime> DataCons { get; set; }
        public string RestSN { get; set; }
        public string NumRest { get; set; }
        public string DataLocalUltimaRest { get; set; }
        public string Observacoes { get; set; }
        public string LiberacaoCredito { get; set; }
        public string Pont { get; set; }
    }
}
