//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LancBancario
    {
        public Nullable<int> Codigo { get; set; }
        public string Operacao { get; set; }
        public string Especie { get; set; }
        public string Banco { get; set; }
        public string Conta { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> Competencia { get; set; }
        public string PlanoContas { get; set; }
        public string NumCheque { get; set; }
        public string Historico { get; set; }
        public Nullable<float> Valor { get; set; }
        public Nullable<float> SaldoAnterior { get; set; }
        public Nullable<float> SaldoAtual { get; set; }
        public int Cod { get; set; }
        public Nullable<decimal> Compensar { get; set; }
        public string Tipo { get; set; }
        public string IDConta { get; set; }
        public string TipoConta { get; set; }
    }
}
