//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinhaEmissaoNFE
    {
        public int ID { get; set; }
        public string CFOPLocal { get; set; }
        public string CFOPInterestadual { get; set; }
        public string CFOPLocalST { get; set; }
        public string CFOPInterestadualST { get; set; }
        public string CSOSN { get; set; }
        public string CSOSNST { get; set; }
        public Nullable<decimal> IPI { get; set; }
        public Nullable<decimal> PIS { get; set; }
        public Nullable<decimal> COFINS { get; set; }
        public string CSTPIS { get; set; }
        public string CSTCOFINS { get; set; }
        public string CSTIPI { get; set; }
        public string DestaqueImpostos { get; set; }
        public string NomeLinha { get; set; }
        public string CSTICMS { get; set; }
    }
}
