//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaNegra
    {
        public string Nome { get; set; }
        public string RazaoSocial { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string CPF_CNPJ { get; set; }
        public string Fone1 { get; set; }
        public string Fone2 { get; set; }
        public string Celular { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Status { get; set; }
        public string RG_InscEst { get; set; }
        public string UF { get; set; }
        public string Tipo { get; set; }
        public string Bairro { get; set; }
        public string Fax { get; set; }
        public string Observacao { get; set; }
        public string NomeTratamento { get; set; }
        public int Codigo { get; set; }
    }
}
