//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local_PCP
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public string Status { get; set; }
        public string Maquina { get; set; }
        public string Equipe { get; set; }
        public string Turno { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
    }
}
