//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multas
    {
        public string Placa { get; set; }
        public string DescricaoVeiculo { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public Nullable<System.DateTime> DataInfracao { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<System.DateTime> Dataindicacao { get; set; }
        public string Motorista { get; set; }
        public string Local { get; set; }
        public string Infracao { get; set; }
        public Nullable<int> Pontos { get; set; }
        public string Gravidade { get; set; }
        public Nullable<float> Valor { get; set; }
        public string Vale { get; set; }
        public string Multas1 { get; set; }
        public string Pago { get; set; }
        public string Multas11 { get; set; }
        public string Multas2 { get; set; }
        public string Multas3 { get; set; }
        public int Codigo { get; set; }
    }
}
