//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCM
    {
        public string COD_NCM { get; set; }
        public string DESC_NCM { get; set; }
        public string CODIGO_NCM { get; set; }
        public Nullable<decimal> Indice { get; set; }
        public Nullable<float> IndiceFederal { get; set; }
        public Nullable<float> IndiceEstadual { get; set; }
        public Nullable<float> IndiceMunicipal { get; set; }
        public Nullable<float> IndiceImportado { get; set; }
    }
}
