//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFEntrada
    {
        public Nullable<int> Codigo { get; set; }
        public string CodFornec { get; set; }
        public string Fornecedor { get; set; }
        public string EnderecoFornec { get; set; }
        public string CidadeFornec { get; set; }
        public string TelefoneFornec { get; set; }
        public string FaxFornec { get; set; }
        public string CepFornec { get; set; }
        public string CMCFornec { get; set; }
        public string CodAtividadeFornec { get; set; }
        public string CNPJFornec { get; set; }
        public string InscEstFornec { get; set; }
        public string TipoNota { get; set; }
        public string NumeroNF { get; set; }
        public string SerieNF { get; set; }
        public string CFOP { get; set; }
        public string DescricaoCFOP { get; set; }
        public string Destinatario { get; set; }
        public string CNPJDestinatario { get; set; }
        public string EnderecoDestinatario { get; set; }
        public string BairroDestinatario { get; set; }
        public string CEPDestinatario { get; set; }
        public string CidadeDestinatario { get; set; }
        public string TelefoneDestinatario { get; set; }
        public string FaxDestinatario { get; set; }
        public string UFDestinatario { get; set; }
        public string UFFornec { get; set; }
        public string InscEstDestinatario { get; set; }
        public Nullable<System.DateTime> DATAEMISSAO { get; set; }
        public Nullable<System.DateTime> DATASAIDA { get; set; }
        public string HORASAIDA { get; set; }
        public string NumFatura1 { get; set; }
        public Nullable<System.DateTime> VencFatura1 { get; set; }
        public Nullable<float> ValorFatura1 { get; set; }
        public string NumFatura2 { get; set; }
        public Nullable<System.DateTime> VencFatura2 { get; set; }
        public Nullable<float> ValorFatura2 { get; set; }
        public string NumFatura3 { get; set; }
        public Nullable<System.DateTime> VencFatura3 { get; set; }
        public Nullable<float> ValorFatura3 { get; set; }
        public string NumFatura4 { get; set; }
        public Nullable<System.DateTime> VencFatura4 { get; set; }
        public Nullable<float> ValorFatura4 { get; set; }
        public string NumFatura5 { get; set; }
        public Nullable<System.DateTime> VencFatura5 { get; set; }
        public Nullable<float> ValorFatura5 { get; set; }
        public string NumFatura6 { get; set; }
        public Nullable<System.DateTime> VencFatura6 { get; set; }
        public Nullable<float> ValorFatura6 { get; set; }
        public Nullable<float> BaseCalculoICMS { get; set; }
        public Nullable<float> ValorICMS { get; set; }
        public Nullable<float> BaseCalculoICMSSubst { get; set; }
        public Nullable<float> ValorICMSSubst { get; set; }
        public Nullable<float> ValorTotalProdutos { get; set; }
        public Nullable<float> ValorFrete { get; set; }
        public Nullable<float> ValorSeguro { get; set; }
        public Nullable<float> OutrasDespesas { get; set; }
        public Nullable<float> ValorIPI { get; set; }
        public Nullable<float> TotalNota { get; set; }
        public string NomeTransp { get; set; }
        public string FreteConta { get; set; }
        public string PlacaTransp { get; set; }
        public string UFTransp1 { get; set; }
        public string CNPJTransp { get; set; }
        public string EnderecoTransp { get; set; }
        public string CidadeTransp { get; set; }
        public string UFTransp2 { get; set; }
        public string InsEstTransp { get; set; }
        public Nullable<float> QuantTransp { get; set; }
        public string EspecieTransp { get; set; }
        public string MarcaTransp { get; set; }
        public string NumeroTransp { get; set; }
        public Nullable<float> PesoBrutoTransp { get; set; }
        public Nullable<float> PesoLiquidoTransp { get; set; }
        public string Observacoes { get; set; }
        public Nullable<float> DescontoTotal { get; set; }
        public string InscEstSubstTrib { get; set; }
        public string Placa { get; set; }
        public string Status { get; set; }
        public string Modelo { get; set; }
        public string Temp { get; set; }
        public string ChaveNFE { get; set; }
    }
}
