//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFSEletr
    {
        public int Numero { get; set; }
        public string NF { get; set; }
        public string Data { get; set; }
        public string IDEmpresa { get; set; }
    }
}
