//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFSE
    {
        public string NaturezaOperacao { get; set; }
        public string RegimeEspecialTributacao { get; set; }
        public string OptanteSimplesNacional { get; set; }
        public string IncentivadorCultural { get; set; }
        public string OutrasInformacoes { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> ValorDeducoes { get; set; }
        public Nullable<decimal> ValorPis { get; set; }
        public Nullable<decimal> ValorCofins { get; set; }
        public Nullable<decimal> ValorInss { get; set; }
        public Nullable<decimal> ValorIr { get; set; }
        public Nullable<decimal> ValorCsll { get; set; }
        public string IssRetido { get; set; }
        public Nullable<decimal> ValorISS { get; set; }
        public Nullable<decimal> OutrasRetencoes { get; set; }
        public Nullable<decimal> DescontoIncondicionado { get; set; }
        public Nullable<decimal> DescontoCondicionado { get; set; }
        public Nullable<decimal> AliquotaServicos { get; set; }
        public Nullable<decimal> BaseCalculo { get; set; }
        public Nullable<decimal> ValorLiquidoNfse { get; set; }
        public string ResponsavelRetencao { get; set; }
        public string CodigoTributacaoMunicipio { get; set; }
        public string DiscriminacaoServicos { get; set; }
        public string ExigibilidadeISS { get; set; }
        public string CpfCnpjCliente { get; set; }
        public string InscricaoMunicipalCliente { get; set; }
        public string RazaoSocialCliente { get; set; }
        public string EnderecoCliente { get; set; }
        public string NumeroCliente { get; set; }
        public string ComplementoCliente { get; set; }
        public string BairroCliente { get; set; }
        public string CodMunicipioCliente { get; set; }
        public string UFCliente { get; set; }
        public string CepCliente { get; set; }
        public string IECliente { get; set; }
        public string TelefoneCliente { get; set; }
        public string EmailCliente { get; set; }
        public Nullable<int> NumNFSE { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Status { get; set; }
    }
}
