//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFSEDados
    {
        public Nullable<int> IDNfse { get; set; }
        public Nullable<int> CodServico { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Quant { get; set; }
        public Nullable<float> ValorUnit { get; set; }
        public Nullable<float> ValorTotal { get; set; }
        public int ID { get; set; }
    }
}
