//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaProdutor
    {
        public int ID { get; set; }
        public string NomeProdutor { get; set; }
        public Nullable<decimal> PesoBrutoCaminhao { get; set; }
        public Nullable<decimal> PesoLiquidoCaminhao { get; set; }
        public Nullable<decimal> Descontos { get; set; }
        public Nullable<decimal> ProducaoLiquidaCampo { get; set; }
        public string UN { get; set; }
        public Nullable<decimal> ValorCusto { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
