//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasNSU
    {
        public int ID { get; set; }
        public string ChaveNFE { get; set; }
        public string CNPJ { get; set; }
        public string Fornecedor { get; set; }
        public string IE { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public string ValorNota { get; set; }
        public Nullable<System.DateTime> DataRecebimento { get; set; }
        public string StatusManifesto { get; set; }
        public string NSU { get; set; }
        public string StatusImportacao { get; set; }
        public string XMLNSU { get; set; }
        public string TipoDocumento { get; set; }
        public string Selecionado { get; set; }
        public string NotaSemManifesto { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string NumeroNF { get; set; }
        public string DestinoOperacao { get; set; }
        public string ConsFinal { get; set; }
        public string CFOPDesc { get; set; }
        public string UFEmit { get; set; }
        public string Presenca { get; set; }
        public string ProcessoAplic { get; set; }
        public string VersaoAplic { get; set; }
        public string FinalidadeNFE { get; set; }
        public string TipoOperacao { get; set; }
        public string NomeFantasia { get; set; }
        public string EnderecoEmit { get; set; }
        public string BairroEmit { get; set; }
        public string CEPEmit { get; set; }
        public string CodMunicipio { get; set; }
        public string MunicipioEmit { get; set; }
        public string FoneEmit { get; set; }
        public string IEST { get; set; }
        public string InscMunicEmit { get; set; }
        public string RegimeTribEmit { get; set; }
        public string IM { get; set; }
        public string Email { get; set; }
        public string BaseCalculoICMS { get; set; }
        public string ValorICMS { get; set; }
        public string ValorICMSDeson { get; set; }
        public string ValorFCP { get; set; }
        public string ValorICMSFCP { get; set; }
        public string ValorICMSUFDest { get; set; }
        public string ValorICMSUFRem { get; set; }
        public string BaseICMSST { get; set; }
        public string ValorICMSST { get; set; }
        public string FCPRetST { get; set; }
        public string FCPRetAntST { get; set; }
        public string ValorFrete { get; set; }
        public string ValorDesconto { get; set; }
        public string ValorII { get; set; }
        public string ValorIPI { get; set; }
        public string ValorIPIDevolvido { get; set; }
        public string ValorPIS { get; set; }
        public string ValorCOFINS { get; set; }
        public string ValorDespAcessorias { get; set; }
        public string ValTotTrib { get; set; }
        public string TipoFrete { get; set; }
        public string ValorSeguro { get; set; }
        public string NumCobr { get; set; }
        public string ValOrig { get; set; }
        public string NumParc1 { get; set; }
        public string VencParc1 { get; set; }
        public string ValorParc1 { get; set; }
        public string NumParc2 { get; set; }
        public string VencParc2 { get; set; }
        public string ValorParc2 { get; set; }
        public string NumParc3 { get; set; }
        public string VencParc3 { get; set; }
        public string ValorParc3 { get; set; }
        public string NumParc4 { get; set; }
        public string VencParc4 { get; set; }
        public string ValorParc4 { get; set; }
        public string NumParc5 { get; set; }
        public string VencParc5 { get; set; }
        public string ValorParc5 { get; set; }
        public string NumParc6 { get; set; }
        public string VencParc6 { get; set; }
        public string ValorParc6 { get; set; }
        public string TagPgto { get; set; }
        public string FormaPgto { get; set; }
        public string InformacoesComplementares { get; set; }
        public Nullable<int> IDCNPJ { get; set; }
        public string NotaCompleta { get; set; }
    }
}
