//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcamentosDados
    {
        public Nullable<int> CodigoOrc { get; set; }
        public string CodigoProduto { get; set; }
        public string Descricao { get; set; }
        public Nullable<float> Quant { get; set; }
        public Nullable<float> ValorUnit { get; set; }
        public Nullable<float> ValorTotal { get; set; }
        public int CodigoItem { get; set; }
        public string CFOP { get; set; }
        public string CFOP1 { get; set; }
        public Nullable<decimal> ValorCusto { get; set; }
        public Nullable<decimal> TotalCusto { get; set; }
        public string Lote { get; set; }
        public string CodBarras { get; set; }
    }
}
