//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orcamentos
    {
        public string Cliente { get; set; }
        public string FoneCliente { get; set; }
        public string FaxCliente { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Vendedor { get; set; }
        public Nullable<float> DescontoReal { get; set; }
        public Nullable<float> DescontoCento { get; set; }
        public Nullable<float> TotalGeral { get; set; }
        public string FormaPGTO { get; set; }
        public string Parcelas { get; set; }
        public int Codigo { get; set; }
        public string Status { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> Pontos { get; set; }
        public Nullable<decimal> ValorPonto { get; set; }
        public Nullable<decimal> TotalPontos { get; set; }
        public Nullable<decimal> TotalCusto { get; set; }
    }
}
