//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcMontadoGrupos
    {
        public Nullable<int> IDOrc { get; set; }
        public string Grupo { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
    }
}
