//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcMontadoDados
    {
        public int ID { get; set; }
        public Nullable<int> CodProduto { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> ValorUnit { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<int> IDAmbiente { get; set; }
        public string CodFornec { get; set; }
        public Nullable<int> IDOrc { get; set; }
        public string Aprovado { get; set; }
        public string UN { get; set; }
        public string Observacao { get; set; }
        public string DescAnterior { get; set; }
        public Nullable<decimal> QtdAnterior { get; set; }
        public Nullable<decimal> ValorUnitAnterior { get; set; }
        public Nullable<decimal> ValorCusto { get; set; }
        public byte[] Imagem { get; set; }
    }
}
