//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcMontado
    {
        public int ID { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public string Cliente { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Status { get; set; }
        public Nullable<int> PedidoAtrelado { get; set; }
        public string Observacao { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public string Vendedor { get; set; }
        public string MensagemPadrao { get; set; }
        public string Profissional { get; set; }
        public string FormaPGTO { get; set; }
        public string TipoDecor { get; set; }
        public string Tema { get; set; }
        public string DataEvento { get; set; }
        public string LocalEvento { get; set; }
        public string CidadeEvento { get; set; }
        public string HorarioEvento { get; set; }
        public string Frete { get; set; }
        public Nullable<decimal> ValorTotalDecor { get; set; }
        public string Entrega { get; set; }
        public string Retirada { get; set; }
        public byte[] Foto { get; set; }
    }
}
