//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int ID { get; set; }
        public string Cliente { get; set; }
        public string Fornecedor { get; set; }
        public string Produtos { get; set; }
        public string CFOP { get; set; }
        public string NCM { get; set; }
        public string SitTributaria { get; set; }
        public string Fabricantes { get; set; }
        public string Veiculos { get; set; }
        public string Transportador { get; set; }
        public string Funcionarios { get; set; }
        public string Contato { get; set; }
        public string Cidades { get; set; }
        public string Ponto { get; set; }
        public string OrdensServiço { get; set; }
        public string Compras { get; set; }
        public string Pedidos { get; set; }
        public string IndiceParcelas { get; set; }
        public string FormasPgto { get; set; }
        public string VendaBalcao { get; set; }
        public string Faturamento { get; set; }
        public string NFEletronica { get; set; }
        public string RelatVendas { get; set; }
        public string RastreamentoVenda { get; set; }
        public string Estoque { get; set; }
        public string TransfFiliais { get; set; }
        public string ContasPagar { get; set; }
        public string ContasReceber { get; set; }
        public string PlanoContas { get; set; }
        public string Bancos { get; set; }
        public string Cheques { get; set; }
        public string Resultados { get; set; }
        public string Fluxograma { get; set; }
        public string ImprimirPreview { get; set; }
        public string AlteraCFOPVenda { get; set; }
        public string CFOPPadrao { get; set; }
        public string LocalXML { get; set; }
        public string MensagemNFE { get; set; }
        public string BancoPreferencia { get; set; }
        public string ContaPreferencia { get; set; }
        public string Aniversarios { get; set; }
        public string VerPagar { get; set; }
        public string EstilosConta { get; set; }
        public string PreVenda { get; set; }
        public string Preco { get; set; }
        public string MARKUP { get; set; }
        public string IndicesPreco { get; set; }
        public string CFOPVenda { get; set; }
        public string Modo { get; set; }
        public Nullable<decimal> Juro { get; set; }
        public string Fiscal { get; set; }
        public string SaldoNegativo { get; set; }
        public string PontoRef { get; set; }
        public string Mensagem { get; set; }
        public string CalcularJuros { get; set; }
        public string ProdutoFilial { get; set; }
        public string FixarDataReceb { get; set; }
        public string ImprimirVenda { get; set; }
        public string FormatoImpresso { get; set; }
        public string ImprimirDireto { get; set; }
        public string Bonificar { get; set; }
        public string Trocas { get; set; }
        public string Degustar { get; set; }
        public string LancarCT { get; set; }
        public string VerificarValidade { get; set; }
        public string ImpressaoRemota { get; set; }
        public string VerificaAgendamento { get; set; }
        public string ClienteCompleto { get; set; }
        public string MontarNFE { get; set; }
        public string AgruparItens { get; set; }
        public string AlterarPreco { get; set; }
        public string TecCli { get; set; }
        public string Producao { get; set; }
        public string EAN { get; set; }
        public string UsarLote { get; set; }
        public Nullable<decimal> AliquotaFiscal { get; set; }
        public string LiberaLimite { get; set; }
        public string Visao { get; set; }
        public string BuscaClienteReceita { get; set; }
        public string MensagemOS { get; set; }
        public string Especificos { get; set; }
        public string ModeloFechamento { get; set; }
        public string ReceberValorVenda { get; set; }
        public string MensagemPadraoOrc { get; set; }
        public string EmitirNFCE { get; set; }
        public string ConsignacaoDupla { get; set; }
        public string MensagemPadraoOrc2 { get; set; }
        public string FormaEmissaoNFSE { get; set; }
        public string VerifComprasAutomatico { get; set; }
        public string VerifEquipamentosAutom { get; set; }
        public string VerifPrevendaAutom { get; set; }
        public string VerifAgendaAut { get; set; }
        public string VerifSolicAutom { get; set; }
        public string VerifMensageiroAut { get; set; }
        public string LimparMemoria { get; set; }
        public string CadEquipamentosFinal { get; set; }
        public string MensagemComodato { get; set; }
        public string CasasDecimaisNFE { get; set; }
        public string NomePrograma { get; set; }
        public string LogoMarca { get; set; }
        public string ImagemP { get; set; }
        public string F8Balcao { get; set; }
        public string DowloadAutomatico { get; set; }
        public Nullable<int> Tempo { get; set; }
        public Nullable<decimal> ValorLimiteDesconto { get; set; }
        public Nullable<decimal> PorcentagemDesconto { get; set; }
    }
}
