//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoContas
    {
        public string Cod_conta { get; set; }
        public Nullable<int> Reduzido { get; set; }
        public string Descricao { get; set; }
        public string Grupo { get; set; }
        public string Nivel { get; set; }
        public string Tipo { get; set; }
        public string Origem { get; set; }
        public string Conta_pai { get; set; }
        public Nullable<double> Debitos { get; set; }
        public Nullable<double> Creditos { get; set; }
        public Nullable<double> Anterior { get; set; }
        public Nullable<double> Atual { get; set; }
        public int field1 { get; set; }
        public string DRE { get; set; }
    }
}
