//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoContasCredito
    {
        public string Conta { get; set; }
        public string GrupoRaiz { get; set; }
        public string Tipo { get; set; }
        public int ID { get; set; }
        public string GrupoPai { get; set; }
        public Nullable<float> ValorEstimado { get; set; }
        public Nullable<float> ValorReal { get; set; }
        public Nullable<float> Diferenca { get; set; }
    }
}
