//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pneus
    {
        public string Pneu { get; set; }
        public string Marca { get; set; }
        public string Dimensao { get; set; }
        public string Construcao { get; set; }
        public string Modelo { get; set; }
        public Nullable<float> KMAcumulado { get; set; }
        public string Lonas { get; set; }
        public string Perimetro { get; set; }
        public Nullable<int> DiasEstoque { get; set; }
        public string NumSerie { get; set; }
        public string Fornecedor { get; set; }
        public string NotaFiscal { get; set; }
        public Nullable<System.DateTime> DataNota { get; set; }
        public Nullable<float> Preco { get; set; }
        public string Local { get; set; }
        public string Veiculo { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public Nullable<float> KmEntrada { get; set; }
        public string Posicao { get; set; }
        public string Eixo { get; set; }
        public string Onde { get; set; }
        public string MotivoSucateamento { get; set; }
        public Nullable<System.DateTime> DataRemessa { get; set; }
        public Nullable<System.DateTime> DataPromessa { get; set; }
        public string Contato { get; set; }
        public string LocalEstoque { get; set; }
    }
}
