//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingProd
    {
        public int Codigo { get; set; }
        public string Descricao { get; set; }
        public Nullable<float> Quant { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalReal { get; set; }
        public string SubGrupo { get; set; }
        public string Grupo { get; set; }
        public Nullable<decimal> Custo { get; set; }
        public Nullable<int> CodProd { get; set; }
        public Nullable<decimal> TotalCusto { get; set; }
        public string Quantidades { get; set; }
        public Nullable<decimal> Entradas { get; set; }
        public Nullable<decimal> EstoqueAtual { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public Nullable<decimal> Bonificado { get; set; }
    }
}
