//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenciasComerciais
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Empresa { get; set; }
        public string Contato { get; set; }
        public string Observacoes { get; set; }
        public string Mediaatraso { get; set; }
        public string CodigoCliente { get; set; }
    }
}
