//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroTransp
    {
        public int Codigo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string Texto { get; set; }
        public string CodigoTransp { get; set; }
        public string Origem { get; set; }
        public string Destino { get; set; }
        public Nullable<float> Tarifa { get; set; }
        public string Produto { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public string Cobrador { get; set; }
        public string PromessaPgto { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> IDClient { get; set; }
    }
}
