//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacaoCompraVenda
    {
        public int ID { get; set; }
        public string ItemCompra { get; set; }
        public string ItemVenda { get; set; }
        public Nullable<float> ValorCompra { get; set; }
        public Nullable<float> ValorVenda { get; set; }
        public Nullable<float> Diferenca { get; set; }
    }
}
