//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatMapa
    {
        public int ID { get; set; }
        public string Cultivar { get; set; }
        public string UF { get; set; }
        public Nullable<float> QtdPlantada { get; set; }
        public Nullable<float> QtdAprovada { get; set; }
        public Nullable<float> Bruta { get; set; }
        public Nullable<float> Beneficiada { get; set; }
        public Nullable<float> Aprovada { get; set; }
        public Nullable<float> QtdUF { get; set; }
        public Nullable<float> QtdFora { get; set; }
        public Nullable<float> QtdExportada { get; set; }
        public Nullable<float> PlantioProprio { get; set; }
        public Nullable<float> OutrasDestinacoes { get; set; }
        public Nullable<float> Saldo { get; set; }
    }
}
