//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representantes
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string CEP { get; set; }
        public string Fone { get; set; }
        public string InscEst { get; set; }
        public string CNPJ { get; set; }
        public string Contato { get; set; }
        public string RegiaoRepresenta { get; set; }
        public string Consideracoes { get; set; }
        public string Estoque { get; set; }
        public Nullable<decimal> Indice { get; set; }
    }
}
