//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int ID { get; set; }
        public string Representante { get; set; }
        public Nullable<int> Codproduto { get; set; }
        public string Produto { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataReserva { get; set; }
    }
}
