//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultMapaProd
    {
        public int ID { get; set; }
        public Nullable<int> IDRelatMapa { get; set; }
        public string Cliente { get; set; }
        public string Documento { get; set; }
        public string CFOP { get; set; }
        public string Data { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string NumDoc { get; set; }
        public string StatusDoc { get; set; }
    }
}
