//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Romaneio
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public string Fornecedor { get; set; }
        public string Produto { get; set; }
        public Nullable<float> QtdVolumes { get; set; }
        public Nullable<float> TaraSaca { get; set; }
        public Nullable<decimal> ValorSaca { get; set; }
        public Nullable<float> PesoBruto { get; set; }
        public Nullable<float> PeloLiquido { get; set; }
        public Nullable<decimal> ValorTotalBruto { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
        public string NumNR { get; set; }
        public Nullable<decimal> Funrural { get; set; }
        public Nullable<decimal> ValorFunrural { get; set; }
        public Nullable<decimal> Adiantamento { get; set; }
        public Nullable<decimal> TotalRomaneio { get; set; }
        public string Corretor { get; set; }
        public string NumDocumento { get; set; }
        public string Obs { get; set; }
    }
}
