//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicos
    {
        public int Cod_Servico { get; set; }
        public string Descricao { get; set; }
        public string Temp_Garantia { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Imposto { get; set; }
        public Nullable<decimal> Valor_S_Imp { get; set; }
        public Nullable<decimal> Comissao { get; set; }
        public string Codigo { get; set; }
        public string Grupo { get; set; }
    }
}
