//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITUACAO_TRIBUTARIA
    {
        public int COD_SITUACAO_TRIBUTARIA { get; set; }
        public string DESCRICAO { get; set; }
        public string COD_ST { get; set; }
        public string SUBSTITUIR { get; set; }
        public Nullable<decimal> Indice { get; set; }
    }
}
