//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_ProcessoDados
    {
        public int ID { get; set; }
        public Nullable<int> IDProcesso { get; set; }
        public string Produto { get; set; }
        public string Grade { get; set; }
        public Nullable<decimal> QtdEstimada { get; set; }
        public Nullable<decimal> QtdProduzida { get; set; }
        public Nullable<decimal> QtdDiferenca { get; set; }
        public Nullable<decimal> CustoEstimado { get; set; }
        public Nullable<decimal> CustoProduzido { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> DataMoldagem { get; set; }
        public Nullable<System.DateTime> DataCostura { get; set; }
        public Nullable<System.DateTime> DataAcabamento { get; set; }
        public Nullable<System.DateTime> DataEmbalagem { get; set; }
        public Nullable<System.DateTime> DataFinalizacao { get; set; }
        public string Observacoes { get; set; }
    }
}
