//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_ProcessoDadosProdutos
    {
        public int ID { get; set; }
        public Nullable<int> IDProcessoDados { get; set; }
        public Nullable<int> IDProduto { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> Custo { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
