//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabAnimais
    {
        public Nullable<int> IDCliente { get; set; }
        public string Tipo { get; set; }
        public string Nome { get; set; }
        public string Raca { get; set; }
        public string Sexo { get; set; }
        public string Cor { get; set; }
        public Nullable<decimal> Idade { get; set; }
        public string Porte { get; set; }
        public string Pelagem { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> DataNasc { get; set; }
        public string Observacoes { get; set; }
    }
}
