//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabBoletimCampo
    {
        public int ID { get; set; }
        public string NumBoletim { get; set; }
        public Nullable<int> IDCampo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Requerente { get; set; }
        public string Endereco { get; set; }
        public string Renasem { get; set; }
        public string Produto { get; set; }
        public string Cultivar { get; set; }
        public Nullable<int> IDProduto { get; set; }
        public string Categoria { get; set; }
        public string Safra { get; set; }
        public Nullable<System.DateTime> DataRecebimento { get; set; }
        public Nullable<System.DateTime> DataConclusaoTeste { get; set; }
        public string DuracaoTeste { get; set; }
        public string NaturezaMaterial { get; set; }
        public string Substrato { get; set; }
        public string Temperatura { get; set; }
        public string Observacoes { get; set; }
    }
}
