//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabBalanco
    {
        public int ID { get; set; }
        public Nullable<int> CodProduto { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> SaldoAnterior { get; set; }
        public Nullable<decimal> Entradas { get; set; }
        public Nullable<decimal> Saidas { get; set; }
        public Nullable<decimal> SaldoFinal { get; set; }
        public Nullable<decimal> EstoqueAtual { get; set; }
        public Nullable<decimal> DiferencaSaldos { get; set; }
        public Nullable<decimal> Contagem { get; set; }
        public Nullable<decimal> DiferencaContagem { get; set; }
        public string NCM { get; set; }
        public string csosn { get; set; }
        public string STrib { get; set; }
        public string CFOP { get; set; }
    }
}
