//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabBoletim
    {
        public int ID { get; set; }
        public string Ano { get; set; }
        public string Coligada { get; set; }
        public string Periodo { get; set; }
        public string Numero { get; set; }
        public string Emitente { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Elaboracao { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<float> Adiantamento { get; set; }
        public Nullable<float> Saldo { get; set; }
        public string Status { get; set; }
    }
}
