//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabCompras
    {
        public int Codigo { get; set; }
        public string Fornecedor { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Comprador { get; set; }
        public string Prazo { get; set; }
        public Nullable<float> IPI { get; set; }
        public string Status { get; set; }
        public string Estado { get; set; }
        public string Produto { get; set; }
    }
}
