//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabCotacao
    {
        public int ID { get; set; }
        public string Comprador { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Obra { get; set; }
        public string Obs { get; set; }
        public string FormaPgto { get; set; }
        public string Parcelas { get; set; }
        public Nullable<decimal> TotalOrcado { get; set; }
        public Nullable<decimal> TotalRealF1 { get; set; }
        public Nullable<decimal> TotalRealF2 { get; set; }
        public Nullable<decimal> TotalRealF3 { get; set; }
        public Nullable<decimal> TotalRealF4 { get; set; }
        public Nullable<decimal> TotalEQF1 { get; set; }
        public Nullable<decimal> TotalEQF2 { get; set; }
        public Nullable<decimal> TotalEQF3 { get; set; }
        public Nullable<decimal> TotalEQF4 { get; set; }
        public string PrazoentregaF1 { get; set; }
        public string PrazoentregaF2 { get; set; }
        public string PrazoentregaF3 { get; set; }
        public string PrazoentregaF4 { get; set; }
        public Nullable<decimal> TotalRealMenorPreco { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalRealF5 { get; set; }
        public Nullable<decimal> TotalRealF6 { get; set; }
        public Nullable<decimal> TotalEQF5 { get; set; }
        public Nullable<decimal> TotalEQF6 { get; set; }
        public string PrazoentregaF5 { get; set; }
        public string PrazoentregaF6 { get; set; }
        public Nullable<decimal> Desvio { get; set; }
    }
}
