//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabEmbarrilar
    {
        public int ID { get; set; }
        public string CodEquipamento { get; set; }
        public string Equipamento { get; set; }
        public Nullable<decimal> QtdReal { get; set; }
        public string ProdutoEmbarrilado { get; set; }
        public Nullable<int> CodProcesso { get; set; }
    }
}
