//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabEstoqueLojas
    {
        public int ID { get; set; }
        public string CNPJ { get; set; }
        public string Filial { get; set; }
        public Nullable<double> Quant { get; set; }
        public Nullable<int> IDProd { get; set; }
    }
}
