//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaPrecoProdutos
    {
        public int ID { get; set; }
        public Nullable<int> IDTabela { get; set; }
        public string Produto { get; set; }
        public string CodBarras { get; set; }
        public Nullable<int> Indice { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public string Modificado { get; set; }
    }
}
