//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaPreco
    {
        public int ID { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> IPI { get; set; }
        public Nullable<decimal> PIS { get; set; }
        public string CSTPis { get; set; }
        public string CSTIpi { get; set; }
        public Nullable<decimal> COFINS { get; set; }
        public string CSTCofins { get; set; }
        public Nullable<decimal> ReducaoIPI { get; set; }
        public Nullable<decimal> ReducaoPIS { get; set; }
        public Nullable<decimal> ReducaoCOFINS { get; set; }
        public Nullable<decimal> ReducaoIPIMenor { get; set; }
        public Nullable<decimal> ReducaoPISMenor { get; set; }
        public Nullable<decimal> ReducaoCOFINSMenor { get; set; }
        public string CSOSN { get; set; }
        public string CSOSNST { get; set; }
        public string SitTrib { get; set; }
    }
}
