//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabFormas
    {
        public string FormaPGTO { get; set; }
        public string DRE { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Executar { get; set; }
        public string Desconsiderar { get; set; }
        public string Conta { get; set; }
        public string Caixa { get; set; }
    }
}
