//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabLista
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public string Cliente { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public Nullable<decimal> Pagar { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<float> X { get; set; }
        public Nullable<float> C { get; set; }
        public Nullable<float> XM { get; set; }
        public Nullable<float> P { get; set; }
        public Nullable<float> L { get; set; }
    }
}
