//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabMultas
    {
        public int ID { get; set; }
        public Nullable<int> IDVenda { get; set; }
        public string Multa { get; set; }
        public string Valor { get; set; }
        public string Lancado { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Local { get; set; }
    }
}
