//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabMDFECte
    {
        public int ID { get; set; }
        public Nullable<int> IDMdfe { get; set; }
        public string ChaveCTE { get; set; }
        public string TipoUnTransporte { get; set; }
        public string PlacaUnTransporte { get; set; }
        public string Lacre { get; set; }
        public string NumLacre { get; set; }
        public string TipoUnCarga { get; set; }
        public string IdUnCarga { get; set; }
        public string LacreUnCarga { get; set; }
        public Nullable<decimal> ValorCTE { get; set; }
        public string ChSegCodBarras { get; set; }
        public Nullable<int> CodMunDescarga { get; set; }
        public string MunDescarga { get; set; }
    }
}
