//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabMinimo
    {
        public int ID { get; set; }
        public string NCM { get; set; }
        public string TipoReducao { get; set; }
        public Nullable<decimal> ValorMinimo { get; set; }
        public Nullable<decimal> ValorMinimoIPI { get; set; }
        public Nullable<decimal> ValorMinimoPIS { get; set; }
        public Nullable<decimal> ValorMinimoCOFINS { get; set; }
    }
}
