//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabMDFE
    {
        public int ID { get; set; }
        public string TipoEmissao { get; set; }
        public string Modal { get; set; }
        public string UFIni { get; set; }
        public string UFFim { get; set; }
        public Nullable<int> CodMunCarreg { get; set; }
        public string MunCarreg { get; set; }
        public string RNTRC { get; set; }
        public string CIOT { get; set; }
        public string VeiculoTracaoCodInt { get; set; }
        public string VeiculoTracaoPlaca { get; set; }
        public string VeiculoTracaoRenavan { get; set; }
        public Nullable<decimal> VeiculoTracaoTara { get; set; }
        public Nullable<decimal> VeiculoTracaoCapacidade { get; set; }
        public Nullable<decimal> VeiculoTracaoCapM3 { get; set; }
        public string VeiculoTracaoTipoRod { get; set; }
        public string VeiculoTracaoTipoCarga { get; set; }
        public string VeiculoTracaoUF { get; set; }
        public string CondutorNome { get; set; }
        public string CondutorCPF { get; set; }
        public string VeiculoReboqueCodInt { get; set; }
        public string VeiculoReboquePlaca { get; set; }
        public string VeiculoReboqueRenavan { get; set; }
        public Nullable<decimal> VeiculoReboqueTara { get; set; }
        public Nullable<decimal> VeiculoReboqueCapacidade { get; set; }
        public Nullable<decimal> VeiculoReboqueCapM3 { get; set; }
        public string VeiculoReboqueTipoRod { get; set; }
        public string VeiculoReboqueTipoCarga { get; set; }
        public string VeiculoReboqueUF { get; set; }
        public string ValePedCNPJForn { get; set; }
        public string ValePedCNPJPg { get; set; }
        public string ValePedNumCompra { get; set; }
        public Nullable<int> QtdCTE { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> PesoTotalCarga { get; set; }
        public string UnidadeMedidaCarga { get; set; }
        public string Observacoes { get; set; }
        public string InformacoesFisco { get; set; }
        public Nullable<int> NumManifesto { get; set; }
        public Nullable<int> QtdNFE { get; set; }
        public Nullable<int> CodMunDescarga { get; set; }
        public string MunDescarga { get; set; }
        public string NumMDFE { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Status { get; set; }
        public string LocalXML { get; set; }
        public string UFPer { get; set; }
        public string RespSeguro { get; set; }
        public string NomeSeguro { get; set; }
        public string SegApolice { get; set; }
        public string Aver { get; set; }
        public string SegCNPJ { get; set; }
        public string NotaCompleta { get; set; }
    }
}
