//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabMDFESeguro
    {
        public int ID { get; set; }
        public Nullable<int> IDMDFE { get; set; }
        public string RespSeguro { get; set; }
        public string NomeSeguro { get; set; }
        public string SegApolice { get; set; }
        public string Aver { get; set; }
        public string SegCNPJ { get; set; }
    }
}
