//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabMDFEMunic
    {
        public int ID { get; set; }
        public Nullable<int> IDMdfe { get; set; }
        public Nullable<int> CodMunDescarga { get; set; }
        public string MunDescarga { get; set; }
        public Nullable<int> IDCte { get; set; }
        public Nullable<int> IDNFe { get; set; }
    }
}
