//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabOSRH
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
        public string UsuarioResp { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public string Cliente { get; set; }
        public string Fone { get; set; }
        public string Contato { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Tipo { get; set; }
        public string VagaFuncao { get; set; }
        public string Sexo { get; set; }
        public string Escolaridade { get; set; }
        public string CNH { get; set; }
        public string ExperienciaAnterior { get; set; }
        public string AtividadeDesenvolvimento { get; set; }
        public string CaracteristicasPessoais { get; set; }
        public string HorarioManha { get; set; }
        public string HorarioSaidaManha { get; set; }
        public string HorarioTarde { get; set; }
        public string HorarioSaidaTarde { get; set; }
        public string Sabado { get; set; }
        public string PodeEstudante { get; set; }
        public string TabNoturno { get; set; }
        public string DomingosFeriados { get; set; }
        public string DispViagens { get; set; }
        public string DispHorasExtras { get; set; }
        public Nullable<decimal> Remuneracao { get; set; }
        public string Comissionado { get; set; }
        public string AjudaCusto { get; set; }
        public string ValorAjuda { get; set; }
        public string ValeTransporte { get; set; }
        public string ValeAlimentacao { get; set; }
        public Nullable<decimal> ValorValeAlimentacao { get; set; }
        public string ValeRefeicao { get; set; }
        public Nullable<decimal> ValorValeRefeicao { get; set; }
        public string PlanoSaude { get; set; }
        public string CestaBasica { get; set; }
        public string OutrasInformacoes { get; set; }
        public string ConfirmaConsulta { get; set; }
        public Nullable<System.DateTime> DataConsulta { get; set; }
        public Nullable<System.DateTime> DataUltimaAlteracao { get; set; }
        public Nullable<System.DateTime> DataFechamento { get; set; }
        public Nullable<System.DateTime> DataPgto { get; set; }
        public Nullable<decimal> ValorOS { get; set; }
        public string ObservacoesDiretoria { get; set; }
        public string Reposicao { get; set; }
        public Nullable<System.DateTime> DataReposicao { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TaxaAbertura { get; set; }
        public Nullable<decimal> TaxaFechamento { get; set; }
    }
}
