//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABOSRHCandidatos
    {
        public int ID { get; set; }
        public Nullable<int> IDOS { get; set; }
        public string Candidato { get; set; }
        public Nullable<System.DateTime> DataEncaminhamento { get; set; }
        public string UsuarioCadastro { get; set; }
        public string HistoricoContatos { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
    }
}
