//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabPrisma
    {
        public int ID { get; set; }
        public Nullable<int> Prisma { get; set; }
        public string Placa { get; set; }
        public string Carro { get; set; }
        public string Marca { get; set; }
        public string Cor { get; set; }
        public string Interna { get; set; }
        public string Externa { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string PrevisaoSaida { get; set; }
        public string HoraConclusao { get; set; }
        public string Status { get; set; }
        public string Localizacao { get; set; }
        public string FormaPgto { get; set; }
        public byte[] Parcelas { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string Supervisor { get; set; }
        public string TempoTotal { get; set; }
        public string Observacoes { get; set; }
        public string CodigoCliente { get; set; }
        public string Cliente { get; set; }
        public string HoraEntrada { get; set; }
        public string Filial { get; set; }
    }
}
