//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabPacotePetDados
    {
        public int ID { get; set; }
        public Nullable<int> IDPacote { get; set; }
        public Nullable<int> IDServico { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> ValorUnit { get; set; }
    }
}
