//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabRegras
    {
        public int ID { get; set; }
        public string DiaSemana { get; set; }
        public string Atividade { get; set; }
        public Nullable<decimal> Valor { get; set; }
    }
}
