//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabSolicitacao
    {
        public int ID { get; set; }
        public string Solicitante { get; set; }
        public string Obra { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Status { get; set; }
        public string PrazoEntrega { get; set; }
        public string StatusAutorizar { get; set; }
        public string Autorizado { get; set; }
        public string DescricaoAutorizar { get; set; }
        public string DiretoriaCiente { get; set; }
        public string LocalAplicacao { get; set; }
        public string LocalEntrega { get; set; }
    }
}
