//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabTermos
    {
        public int ID { get; set; }
        public Nullable<int> IDBoletim { get; set; }
        public string NumTermo { get; set; }
        public string NomeTecnico { get; set; }
        public string CREA { get; set; }
        public string CPF { get; set; }
        public string RENASEM { get; set; }
        public string Endereco { get; set; }
        public string Fone { get; set; }
        public string Cidade { get; set; }
        public string ProdutoVinculado { get; set; }
        public Nullable<int> IDProdutoVinculado { get; set; }
        public string Cultivar { get; set; }
        public string Categoria { get; set; }
        public string Safra { get; set; }
        public string NomeProdutor { get; set; }
        public string CNPJProdutor { get; set; }
        public string EnderecoProdutor { get; set; }
        public string Cidadeprodutor { get; set; }
        public string CEPProdutor { get; set; }
        public string RENASEMResp { get; set; }
        public string FoneResp { get; set; }
    }
}
