//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabTecidos
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Tecido { get; set; }
        public string Composicao { get; set; }
        public string Encolhimento { get; set; }
        public string Largura { get; set; }
    }
}
