//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp
    {
        public string Solicitado { get; set; }
        public string Executado { get; set; }
        public string OS { get; set; }
        public Nullable<float> Valor { get; set; }
        public string Peca { get; set; }
        public string Referencia { get; set; }
        public Nullable<float> Quant { get; set; }
        public Nullable<float> Valor2 { get; set; }
        public string Vendedor { get; set; }
        public int ID { get; set; }
    }
}
