//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempLancBancario
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Historico { get; set; }
        public Nullable<decimal> Compensar { get; set; }
        public Nullable<decimal> SaldoAnterior { get; set; }
        public Nullable<decimal> SaldoAtual { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string NumCheque { get; set; }
        public string Operacao { get; set; }
    }
}
