//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempNFE
    {
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public Nullable<float> Quant { get; set; }
        public Nullable<float> Custo { get; set; }
        public Nullable<float> Total { get; set; }
        public string CFOP { get; set; }
        public string Fornecedor { get; set; }
        public string DataEntrada { get; set; }
        public string FormaPgto { get; set; }
    }
}
