//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempFechamento
    {
        public int ID { get; set; }
        public string Usuario { get; set; }
        public Nullable<decimal> TotalVenda { get; set; }
        public Nullable<decimal> TotalVendaSaldo { get; set; }
        public Nullable<decimal> TotalSangrias { get; set; }
        public string Periodo { get; set; }
        public Nullable<decimal> Digitado { get; set; }
    }
}
