//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempVacina
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DataVacina { get; set; }
        public Nullable<System.DateTime> DataValidade { get; set; }
        public string Animal { get; set; }
        public string Raca { get; set; }
        public string Proprietario { get; set; }
        public string Cidade { get; set; }
        public string Endereco { get; set; }
        public string Fone { get; set; }
    }
}
