//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempVendadados
    {
        public int ID { get; set; }
        public Nullable<int> CodigoProduto { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> ValorUnit { get; set; }
        public string Operador { get; set; }
        public string Local { get; set; }
        public Nullable<decimal> Quant { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string Excessoes { get; set; }
    }
}
