//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermoBoletimDados
    {
        public int ID { get; set; }
        public Nullable<int> NumBoletim { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Lote { get; set; }
        public string Pen { get; set; }
        public Nullable<double> Analisado { get; set; }
        public Nullable<double> SCAnalisado { get; set; }
        public Nullable<System.DateTime> DataTermo { get; set; }
        public string Termo { get; set; }
        public Nullable<double> QtdSc { get; set; }
        public Nullable<double> PesoSc { get; set; }
        public Nullable<double> TTermo { get; set; }
        public Nullable<double> Faturamento { get; set; }
        public Nullable<double> Devolvido { get; set; }
        public Nullable<double> Venda { get; set; }
        public Nullable<double> Estoque { get; set; }
        public Nullable<double> EstoqueReal { get; set; }
        public Nullable<double> Saldo { get; set; }
    }
}
