//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportadora
    {
        public string Fantasia { get; set; }
        public string Endereco { get; set; }
        public string UF { get; set; }
        public string Fone { get; set; }
        public string Contato { get; set; }
        public string Produto { get; set; }
        public string Email { get; set; }
        public int Codigo { get; set; }
        public string IE { get; set; }
        public string CNPJ { get; set; }
        public string HomePage { get; set; }
        public string Cidade { get; set; }
        public string RazaoSocial { get; set; }
        public string Transportadora1 { get; set; }
        public string Localidade { get; set; }
        public string Placa { get; set; }
        public string UFPlaca { get; set; }
    }
}
