//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TributoAtacado
    {
        public int Codigo { get; set; }
        public Nullable<float> PIS { get; set; }
        public Nullable<float> COFINS { get; set; }
        public Nullable<float> ICMS { get; set; }
        public Nullable<float> COMISSAO { get; set; }
        public Nullable<float> CUSTOFIXO { get; set; }
        public Nullable<float> CUSTOFINANCEIRO { get; set; }
        public Nullable<float> MargemLucro { get; set; }
        public Nullable<float> PisVenda { get; set; }
        public Nullable<float> IPIVenda { get; set; }
        public Nullable<float> ICMSVenda { get; set; }
        public Nullable<float> CofinsVenda { get; set; }
        public Nullable<float> Frete { get; set; }
    }
}
