//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trocas
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Cliente { get; set; }
        public string Produto { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> NumVenda { get; set; }
        public Nullable<decimal> Qtd { get; set; }
        public Nullable<decimal> Unit { get; set; }
    }
}
