//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnProd
    {
        public int ID { get; set; }
        public Nullable<int> CodProd { get; set; }
        public string Un { get; set; }
        public Nullable<decimal> Qtd { get; set; }
    }
}
