//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValeFunc
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Funcionario { get; set; }
        public string Descricao { get; set; }
        public Nullable<float> Valor { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Ano { get; set; }
    }
}
