//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaDadosNFE
    {
        public Nullable<int> CodigoVenda { get; set; }
        public string CodigoProduto { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Quant { get; set; }
        public Nullable<decimal> ValorUnit { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string SitTribut { get; set; }
        public Nullable<float> IPI { get; set; }
        public string ClassFiscal { get; set; }
        public string Estoque { get; set; }
        public string Local { get; set; }
        public int CodigoItem { get; set; }
        public Nullable<float> ICMS { get; set; }
        public string CFOP { get; set; }
        public string CFOP1 { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public string NCM { get; set; }
        public string Operador { get; set; }
        public Nullable<decimal> MVA { get; set; }
        public Nullable<System.DateTime> Validade { get; set; }
        public string Selecionado { get; set; }
        public string Status { get; set; }
        public Nullable<int> CodBonif { get; set; }
        public Nullable<decimal> Pauta { get; set; }
        public string Lote { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Campo { get; set; }
        public Nullable<decimal> TamPP { get; set; }
        public Nullable<decimal> TamP { get; set; }
        public Nullable<decimal> TamM { get; set; }
        public Nullable<decimal> TamG { get; set; }
        public Nullable<decimal> TamGG { get; set; }
        public Nullable<decimal> Tam3G { get; set; }
        public Nullable<decimal> Tam4G { get; set; }
        public Nullable<decimal> Tam5G { get; set; }
        public Nullable<decimal> Tam6G { get; set; }
        public Nullable<decimal> TamG1 { get; set; }
        public Nullable<decimal> TamG2 { get; set; }
        public string IPR { get; set; }
        public string Safra { get; set; }
        public string Germinacao { get; set; }
        public string Peneira { get; set; }
        public string Boletim { get; set; }
        public string Termo { get; set; }
        public string Vigor { get; set; }
        public string Area { get; set; }
        public Nullable<System.DateTime> DataPlantio { get; set; }
        public Nullable<System.DateTime> DataBeneficiamento { get; set; }
        public Nullable<System.DateTime> DataColheita { get; set; }
        public Nullable<decimal> QtdAnalisado { get; set; }
        public Nullable<decimal> ScAnalisaco { get; set; }
        public Nullable<decimal> QtdSacas { get; set; }
        public Nullable<decimal> PesoSacas { get; set; }
        public string NumNFE { get; set; }
        public string UN { get; set; }
        public Nullable<decimal> ValorDesconto { get; set; }
        public Nullable<decimal> BaseICMS { get; set; }
        public Nullable<decimal> ValorICMS { get; set; }
        public Nullable<decimal> ValorIPI { get; set; }
        public Nullable<decimal> AliquotaICMS { get; set; }
        public Nullable<decimal> AliquotaIPI { get; set; }
        public Nullable<decimal> AliquotaPIS { get; set; }
        public Nullable<decimal> ValorPIS { get; set; }
        public Nullable<decimal> AliquotaCOFINS { get; set; }
        public Nullable<decimal> ValorCOFINS { get; set; }
        public string ItemPed { get; set; }
        public string xPed { get; set; }
    }
}
