//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaPeriodo
    {
        public int ID { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> CodCliente { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> Janeiro { get; set; }
        public Nullable<decimal> Fevereiro { get; set; }
        public Nullable<decimal> Marco { get; set; }
        public Nullable<decimal> Abril { get; set; }
        public Nullable<decimal> Maio { get; set; }
        public Nullable<decimal> Junho { get; set; }
        public Nullable<decimal> Julho { get; set; }
        public Nullable<decimal> Agosto { get; set; }
        public Nullable<decimal> Setembro { get; set; }
        public Nullable<decimal> Outubro { get; set; }
        public Nullable<decimal> Novembro { get; set; }
        public Nullable<decimal> Dezembro { get; set; }
    }
}
