//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Origem
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaNFE
    {
        public string Cliente { get; set; }
        public string FoneCliente { get; set; }
        public string FaxCliente { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Vendedor { get; set; }
        public Nullable<decimal> DescontoReal { get; set; }
        public Nullable<decimal> DescontoCento { get; set; }
        public Nullable<decimal> TotalGeral { get; set; }
        public string FormaPGTO { get; set; }
        public string Parcelas { get; set; }
        public string Status { get; set; }
        public string Observacao { get; set; }
        public string QuemAtende { get; set; }
        public string CFOP1 { get; set; }
        public string CFOP { get; set; }
        public string InscSubstEst { get; set; }
        public string Numero1 { get; set; }
        public string Numero2 { get; set; }
        public string Numero3 { get; set; }
        public string Numero4 { get; set; }
        public string Numero5 { get; set; }
        public string Numero6 { get; set; }
        public string Numero7 { get; set; }
        public string Numero8 { get; set; }
        public string Numero9 { get; set; }
        public string Numero10 { get; set; }
        public string Numero11 { get; set; }
        public string Numero12 { get; set; }
        public string Vencimento1 { get; set; }
        public string Vencimento2 { get; set; }
        public string Vencimento3 { get; set; }
        public string Vencimento4 { get; set; }
        public string Vencimento5 { get; set; }
        public string Vencimento6 { get; set; }
        public string Vencimento7 { get; set; }
        public string Vencimento8 { get; set; }
        public string Vencimento9 { get; set; }
        public string Vencimento10 { get; set; }
        public string Vencimento11 { get; set; }
        public string Vencimento12 { get; set; }
        public Nullable<float> Valor1 { get; set; }
        public Nullable<float> Valor2 { get; set; }
        public Nullable<float> Valor3 { get; set; }
        public Nullable<float> Valor4 { get; set; }
        public Nullable<float> Valor5 { get; set; }
        public Nullable<float> Valor6 { get; set; }
        public Nullable<float> Valor7 { get; set; }
        public Nullable<float> Valor8 { get; set; }
        public Nullable<float> Valor9 { get; set; }
        public Nullable<float> Valor10 { get; set; }
        public Nullable<float> Valor11 { get; set; }
        public Nullable<float> Valor12 { get; set; }
        public Nullable<float> Comissao { get; set; }
        public Nullable<float> ValorICMS { get; set; }
        public Nullable<float> ValorFrete { get; set; }
        public Nullable<float> ValorIPI { get; set; }
        public string Transportadora { get; set; }
        public string FreteConta { get; set; }
        public string PlacaVeiculo { get; set; }
        public string CGCTransportadora { get; set; }
        public string EnderecoTransportadora { get; set; }
        public string CidadeTransportadora { get; set; }
        public string InscEstTransportadora { get; set; }
        public Nullable<float> QuantTransportadora { get; set; }
        public string EspecieTransportadora { get; set; }
        public string MarcaTransportadora { get; set; }
        public string NumTransportadora { get; set; }
        public Nullable<float> PesoTransportadora { get; set; }
        public Nullable<float> PesoLiquidoTransportadora { get; set; }
        public string DadosAdicionais { get; set; }
        public Nullable<decimal> Lucro { get; set; }
        public Nullable<float> BaseCalculo { get; set; }
        public string Status2 { get; set; }
        public string CodPedido { get; set; }
        public string Filial { get; set; }
        public string Transmitido { get; set; }
        public string Mesa { get; set; }
        public string HoraEntrada { get; set; }
        public string PrevisaoSaida { get; set; }
        public string Entregador { get; set; }
        public string LocalXML { get; set; }
        public Nullable<int> CodigoVenda { get; set; }
        public int Codigo { get; set; }
        public string CSOSN { get; set; }
        public string CRN { get; set; }
        public string IPICST { get; set; }
        public string PISCST { get; set; }
        public string COFINSCST { get; set; }
        public Nullable<int> NumNFE { get; set; }
        public string Tipo { get; set; }
        public string NFE { get; set; }
        public string NotaCompleta { get; set; }
        public string Status3 { get; set; }
        public string NotaFiscal { get; set; }
        public string AutoSenha { get; set; }
        public Nullable<System.DateTime> DataNF { get; set; }
        public string JustificativaContingencia { get; set; }
        public string TagPgto { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
        public Nullable<System.DateTime> DataRecolha { get; set; }
        public Nullable<decimal> OutrosValores { get; set; }
        public Nullable<decimal> ValorSeguro { get; set; }
        public string FinalidadeNFE { get; set; }
        public string InformFisco { get; set; }
        public string ChaveNFERef { get; set; }
        public string ChaveNFE { get; set; }
        public Nullable<decimal> BaseICMS { get; set; }
        public Nullable<decimal> ICMS { get; set; }
        public Nullable<decimal> BaseST { get; set; }
        public Nullable<decimal> ICMSST { get; set; }
        public Nullable<decimal> IPI { get; set; }
        public Nullable<decimal> PIS { get; set; }
        public Nullable<decimal> COFINS { get; set; }
        public string TabelaPreco { get; set; }
        public string ObservacaoComercial { get; set; }
        public string ObservacaoFinanceira { get; set; }
        public string VendaPresencial { get; set; }
        public string DestinoOperacao { get; set; }
        public string StatusMovimento { get; set; }
        public string FinanceiroLiberado { get; set; }
        public string ComercialLiberado { get; set; }
        public Nullable<decimal> ComissaoVendedor { get; set; }
        public string Vendedor2 { get; set; }
        public Nullable<decimal> ComissaoVendedor2 { get; set; }
        public string Vendedor3 { get; set; }
        public Nullable<decimal> ComissaoVendedor3 { get; set; }
        public string Vendedor4 { get; set; }
        public Nullable<decimal> ComissaoVendedor4 { get; set; }
        public string Vendedor5 { get; set; }
        public Nullable<decimal> ComissaoVendedor5 { get; set; }
        public Nullable<decimal> ValorNF { get; set; }
        public string MensagemCFOP { get; set; }
        public Nullable<int> NumNFCE { get; set; }
        public string LocalXML2 { get; set; }
        public string NFTerceiros { get; set; }
        public string Financeiro { get; set; }
        public string Endereco { get; set; }
        public string PontoRef { get; set; }
        public string Bairro { get; set; }
        public string Fone { get; set; }
        public string Celular { get; set; }
        public string Cidade { get; set; }
        public string Logistica { get; set; }
        public Nullable<System.DateTime> DataInicioLogistica { get; set; }
        public Nullable<System.DateTime> DataUltimoEstadoLogistica { get; set; }
        public Nullable<System.DateTime> DataConclusaoLogistica { get; set; }
        public string Comanda { get; set; }
        public Nullable<decimal> BaseFCP { get; set; }
        public Nullable<decimal> PorcentagemFCP { get; set; }
        public Nullable<decimal> ValorFCP { get; set; }
        public string IndicarFCP { get; set; }
        public Nullable<int> CodCli { get; set; }
        public string LocalCCE { get; set; }
        public string ProtocoloNFE { get; set; }
        public string Veiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<float> Cubico { get; set; }
        public string Campo { get; set; }
        public string IDPedidoExterno { get; set; }
    }
}
