//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class balancoproduto
    {
        public int BalancoProdutoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public Nullable<int> BALANCOID { get; set; }
        public Nullable<int> PRODUTOID { get; set; }
        public decimal QUANTIDADECONTAGEM { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_01 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_02 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_03 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_04 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_05 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_06 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_07 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_08 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_09 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_10 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_11 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_12 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_13 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_14 { get; set; }
        public decimal QUANTIDADECONTAGEM_GRADE_15 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_01 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_02 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_03 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_04 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_05 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_06 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_07 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_08 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_09 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_10 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_11 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_12 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_13 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_14 { get; set; }
        public decimal QUANTIDADEMOVIMENTADA_GRADE_15 { get; set; }
    
        public virtual balanco balanco { get; set; }
        public virtual produto produto { get; set; }
    }
}
