//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class caixa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caixa()
        {
            this.caixamovimento = new HashSet<caixamovimento>();
        }
    
        public int CaixaId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public Nullable<System.DateTime> DATACONFERENCIA { get; set; }
        public Nullable<System.DateTime> DATAFECHAMENTO { get; set; }
        public Nullable<int> SEGURANCAUSUARIOID { get; set; }
        public decimal VALOR_ABERTURA { get; set; }
        public decimal VALOR_FECHAMENTO { get; set; }
        public decimal VALOR_FECHAMENTO_CARTAO { get; set; }
        public decimal VALOR_FECHAMENTO_CHEQUE { get; set; }
        public decimal VALOR_FECHAMENTO_DINHEIRO { get; set; }
        public decimal VALOR_CONFERENCIA { get; set; }
        public decimal VALOR_CONFERENCIA_CARTAO { get; set; }
        public decimal VALOR_CONFERENCIA_CHEQUE { get; set; }
        public decimal VALOR_CONFERENCIA_DINHEIRO { get; set; }
        public decimal VALOR_FUNDO_CAIXA { get; set; }
    
        public virtual segurancausuario segurancausuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caixamovimento> caixamovimento { get; set; }
    }
}
