//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class cep
    {
        public int CepId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public bool ATIVO { get; set; }
        public Nullable<int> BAIRROID { get; set; }
        public string CEP1 { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public string LOGRADOURO { get; set; }
    
        public virtual bairro bairro { get; set; }
    }
}
