//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cidade()
        {
            this.bairro = new HashSet<bairro>();
        }
    
        public int CidadeId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public string CODIGOIBGE { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public string FAIXA_CEP_INICIAL { get; set; }
        public string FAIXA_CEP_FINAL { get; set; }
        public string NOME { get; set; }
        public Nullable<int> UFID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bairro> bairro { get; set; }
        public virtual uf uf { get; set; }
    }
}
