//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracaoetiqueta
    {
        public int ConfiguracaoEtiquetaId { get; set; }
        public string DESCRICAO { get; set; }
        public string CONFIGURACAO { get; set; }
        public Nullable<System.DateTime> ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
    }
}
