//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracaopagamento
    {
        public int ConfiguracaoPagamentoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public int TIPO_PAGAMENTO_CARTAODECREDITO { get; set; }
        public int TIPO_PAGAMENTO_PROMISSORIA { get; set; }
        public int TIPO_PAGAMENTO_TRANSFERENCIA { get; set; }
        public int TIPO_PAGAMENTO_CARTEIRA { get; set; }
        public int TIPO_PAGAMENTO_CHEQUE { get; set; }
        public int TIPO_PAGAMENTO_CREDIARIO { get; set; }
        public int TIPO_PAGAMENTO_DUPLICATA { get; set; }
        public int TIPO_PAGAMENTO_BOLETO { get; set; }
        public int TIPO_PAGAMENTO_DINHEIRO { get; set; }
        public int TIPO_PAGAMENTO_DEBITO { get; set; }
        public int TIPO_PAGAMENTO_TICKET { get; set; }
        public int TIPO_PAGAMENTO_CREDITO { get; set; }
        public bool UTILIZARCONFIGURACAOPAGAMENTO { get; set; }
    }
}
