//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoqueprodutomovimento
    {
        public int EstoqueProdutoMovimentoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public decimal ESTOQUEATUAL { get; set; }
        public decimal GRADE_QUANTIDADE_01 { get; set; }
        public decimal GRADE_QUANTIDADE_02 { get; set; }
        public decimal GRADE_QUANTIDADE_03 { get; set; }
        public decimal GRADE_QUANTIDADE_04 { get; set; }
        public decimal GRADE_QUANTIDADE_05 { get; set; }
        public decimal GRADE_QUANTIDADE_06 { get; set; }
        public decimal GRADE_QUANTIDADE_07 { get; set; }
        public decimal GRADE_QUANTIDADE_08 { get; set; }
        public decimal GRADE_QUANTIDADE_09 { get; set; }
        public decimal GRADE_QUANTIDADE_10 { get; set; }
        public decimal GRADE_QUANTIDADE_11 { get; set; }
        public decimal GRADE_QUANTIDADE_12 { get; set; }
        public decimal GRADE_QUANTIDADE_13 { get; set; }
        public decimal GRADE_QUANTIDADE_14 { get; set; }
        public decimal GRADE_QUANTIDADE_15 { get; set; }
        public Nullable<int> PESSOAID { get; set; }
        public Nullable<int> PRODUTOID { get; set; }
        public int ORIGEMMOVIMENTO { get; set; }
        public string GRADE_REFERENCIA_01 { get; set; }
        public string GRADE_REFERENCIA_02 { get; set; }
        public string GRADE_REFERENCIA_03 { get; set; }
        public string GRADE_REFERENCIA_04 { get; set; }
        public string GRADE_REFERENCIA_05 { get; set; }
        public string GRADE_REFERENCIA_06 { get; set; }
        public string GRADE_REFERENCIA_07 { get; set; }
        public string GRADE_REFERENCIA_08 { get; set; }
        public string GRADE_REFERENCIA_09 { get; set; }
        public string GRADE_REFERENCIA_10 { get; set; }
        public string GRADE_REFERENCIA_11 { get; set; }
        public string GRADE_REFERENCIA_12 { get; set; }
        public string GRADE_REFERENCIA_13 { get; set; }
        public string GRADE_REFERENCIA_14 { get; set; }
        public string GRADE_REFERENCIA_15 { get; set; }
        public string OBSERVACAO { get; set; }
    
        public virtual pessoa pessoa { get; set; }
        public virtual produto produto { get; set; }
    }
}
