//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class fecpexcecoes
    {
        public int FECPExcecoesId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ISATIVO { get; set; }
        public Nullable<int> CLASSIFICACAOFISCAL_ID { get; set; }
        public Nullable<int> UF_ID { get; set; }
        public decimal ALIQUOTA { get; set; }
        public decimal ALIQUOTA_ICMS { get; set; }
    
        public virtual classificacaofiscal classificacaofiscal { get; set; }
    }
}
