//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class formarecebimento
    {
        public int FormaRecebimentoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public bool ISDINHEIRO { get; set; }
        public int DINHEIRO_ORDEM { get; set; }
        public bool ISCHEQUERECEBIDO { get; set; }
        public int CHEQUERECEBIDO_ORDEM { get; set; }
        public bool ISCARTAOCREDITO { get; set; }
        public int CARTAOCREDITO_ORDEM { get; set; }
        public bool ISCARTAODEBITO { get; set; }
        public int CARTAODEBITO_ORDEM { get; set; }
        public bool ISPROMISSORIA { get; set; }
        public int PROMISSORIA_ORDEM { get; set; }
        public bool ISDUPLICATA { get; set; }
        public int DUPLICATA_ORDEM { get; set; }
        public bool ISCREDITO { get; set; }
        public int CREDITO_ORDEM { get; set; }
        public bool ISTRANSFERENCIA { get; set; }
        public int TRANSFERENCIA_ORDEM { get; set; }
        public bool ISBOLETO { get; set; }
        public int BOLETO_ORDEM { get; set; }
        public bool ISVALETICKET { get; set; }
        public int VALETICKET_ORDEM { get; set; }
        public bool ISCARTEIRA { get; set; }
        public int CARTEIRA_ORDEM { get; set; }
        public bool ISCREDIARIO { get; set; }
        public int CREDIARIO_ORDEM { get; set; }
    }
}
