//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class grade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grade()
        {
            this.produto = new HashSet<produto>();
        }
    
        public int GradeId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ISATIVO { get; set; }
        public string NOME { get; set; }
        public string OBSERVACAO { get; set; }
        public string TAMANHO_01 { get; set; }
        public string TAMANHO_01_LEGENDA { get; set; }
        public string TAMANHO_02 { get; set; }
        public string TAMANHO_02_LEGENDA { get; set; }
        public string TAMANHO_03 { get; set; }
        public string TAMANHO_03_LEGENDA { get; set; }
        public string TAMANHO_04 { get; set; }
        public string TAMANHO_04_LEGENDA { get; set; }
        public string TAMANHO_05 { get; set; }
        public string TAMANHO_05_LEGENDA { get; set; }
        public string TAMANHO_06 { get; set; }
        public string TAMANHO_06_LEGENDA { get; set; }
        public string TAMANHO_07 { get; set; }
        public string TAMANHO_07_LEGENDA { get; set; }
        public string TAMANHO_08 { get; set; }
        public string TAMANHO_08_LEGENDA { get; set; }
        public string TAMANHO_09 { get; set; }
        public string TAMANHO_09_LEGENDA { get; set; }
        public string TAMANHO_10 { get; set; }
        public string TAMANHO_10_LEGENDA { get; set; }
        public string TAMANHO_11 { get; set; }
        public string TAMANHO_11_LEGENDA { get; set; }
        public string TAMANHO_12 { get; set; }
        public string TAMANHO_12_LEGENDA { get; set; }
        public string TAMANHO_13 { get; set; }
        public string TAMANHO_13_LEGENDA { get; set; }
        public string TAMANHO_14 { get; set; }
        public string TAMANHO_14_LEGENDA { get; set; }
        public string TAMANHO_15 { get; set; }
        public string TAMANHO_15_LEGENDA { get; set; }
        public string TAMANHO_01_REFERENCIA { get; set; }
        public string TAMANHO_02_REFERENCIA { get; set; }
        public string TAMANHO_03_REFERENCIA { get; set; }
        public string TAMANHO_04_REFERENCIA { get; set; }
        public string TAMANHO_05_REFERENCIA { get; set; }
        public string TAMANHO_06_REFERENCIA { get; set; }
        public string TAMANHO_07_REFERENCIA { get; set; }
        public string TAMANHO_08_REFERENCIA { get; set; }
        public string TAMANHO_09_REFERENCIA { get; set; }
        public string TAMANHO_10_REFERENCIA { get; set; }
        public string TAMANHO_11_REFERENCIA { get; set; }
        public string TAMANHO_12_REFERENCIA { get; set; }
        public string TAMANHO_13_REFERENCIA { get; set; }
        public string TAMANHO_14_REFERENCIA { get; set; }
        public string TAMANHO_15_REFERENCIA { get; set; }
        public string CADASTROUSUARIO { get; set; }
        public long WEB_KEY { get; set; }
        public Nullable<System.DateTime> SINCRONIZADO_EM { get; set; }
        public long HUB_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produto> produto { get; set; }
    }
}
