//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagemproduto
    {
        public int ImagemProdutoId { get; set; }
        public int ProdutoId { get; set; }
        public byte[] IMAGEM { get; set; }
        public byte[] IMAGEM_REDUZIDA { get; set; }
        public string IMAGEM_MD5 { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public string CADASTROUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ISATIVO { get; set; }
        public long WEB_KEY { get; set; }
        public Nullable<System.DateTime> SINCRONIZADO_EM { get; set; }
    
        public virtual produto produto { get; set; }
    }
}
