//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int LogId { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Acao { get; set; }
        public string Query { get; set; }
        public int IDALTERADO { get; set; }
        public string TabelaAlvo { get; set; }
        public int IDUSUARIO { get; set; }
        public string USUARIO { get; set; }
        public int EMPRESAID { get; set; }
        public string COMPUTADOR { get; set; }
        public string IPCOMPUTADOR { get; set; }
    }
}
