//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class virgemEntities : DbContext
    {
        public virgemEntities()
            : base("name=virgemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public virtual DbSet<bairro> bairro { get; set; }
        public virtual DbSet<balanco> balanco { get; set; }
        public virtual DbSet<balancoproduto> balancoproduto { get; set; }
        public virtual DbSet<banco> banco { get; set; }
        public virtual DbSet<caixa> caixa { get; set; }
        public virtual DbSet<caixamovimento> caixamovimento { get; set; }
        public virtual DbSet<cep> cep { get; set; }
        public virtual DbSet<cestncm> cestncm { get; set; }
        public virtual DbSet<cfopregrasubstituicao> cfopregrasubstituicao { get; set; }
        public virtual DbSet<cidade> cidade { get; set; }
        public virtual DbSet<classificacaofiscal> classificacaofiscal { get; set; }
        public virtual DbSet<colecao> colecao { get; set; }
        public virtual DbSet<configuracaoetiqueta> configuracaoetiqueta { get; set; }
        public virtual DbSet<configuracaogeral> configuracaogeral { get; set; }
        public virtual DbSet<configuracaopagamento> configuracaopagamento { get; set; }
        public virtual DbSet<contaspagarreceberparcela> contaspagarreceberparcela { get; set; }
        public virtual DbSet<crediario> crediario { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<estoqueproduto> estoqueproduto { get; set; }
        public virtual DbSet<estoqueprodutomovimento> estoqueprodutomovimento { get; set; }
        public virtual DbSet<fabricante> fabricante { get; set; }
        public virtual DbSet<fecpexcecoes> fecpexcecoes { get; set; }
        public virtual DbSet<formarecebimento> formarecebimento { get; set; }
        public virtual DbSet<grade> grade { get; set; }
        public virtual DbSet<grupo> grupo { get; set; }
        public virtual DbSet<imagemproduto> imagemproduto { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<movimentodecontas> movimentodecontas { get; set; }
        public virtual DbSet<notafiscal> notafiscal { get; set; }
        public virtual DbSet<notafiscal_cartacorrecao> notafiscal_cartacorrecao { get; set; }
        public virtual DbSet<notafiscal_pedido> notafiscal_pedido { get; set; }
        public virtual DbSet<notafiscalproduto> notafiscalproduto { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<pedidoproduto> pedidoproduto { get; set; }
        public virtual DbSet<pessoa> pessoa { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<produtokitcomposicao> produtokitcomposicao { get; set; }
        public virtual DbSet<referencia> referencia { get; set; }
        public virtual DbSet<regracomissao> regracomissao { get; set; }
        public virtual DbSet<regracomissaocolecao> regracomissaocolecao { get; set; }
        public virtual DbSet<regracomissaofornecedor> regracomissaofornecedor { get; set; }
        public virtual DbSet<regracomissaogrupo> regracomissaogrupo { get; set; }
        public virtual DbSet<regracomissaomarca> regracomissaomarca { get; set; }
        public virtual DbSet<regracomissaoproduto> regracomissaoproduto { get; set; }
        public virtual DbSet<segurancaperfil> segurancaperfil { get; set; }
        public virtual DbSet<segurancaperfilpermissao> segurancaperfilpermissao { get; set; }
        public virtual DbSet<segurancausuario> segurancausuario { get; set; }
        public virtual DbSet<setor> setor { get; set; }
        public virtual DbSet<setorproduto> setorproduto { get; set; }
        public virtual DbSet<sincronizacao> sincronizacao { get; set; }
        public virtual DbSet<subgrupo> subgrupo { get; set; }
        public virtual DbSet<transferenciaestoque> transferenciaestoque { get; set; }
        public virtual DbSet<transferenciaestoqueproduto> transferenciaestoqueproduto { get; set; }
        public virtual DbSet<uf> uf { get; set; }
        public virtual DbSet<unidade> unidade { get; set; }
    }
}
