//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class notafiscal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notafiscal()
        {
            this.notafiscal_cartacorrecao = new HashSet<notafiscal_cartacorrecao>();
            this.notafiscalproduto = new HashSet<notafiscalproduto>();
        }
    
        public int NotaFiscalId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public int MODELONOTA { get; set; }
        public Nullable<int> PESSOAID { get; set; }
        public Nullable<int> VENDEDORID { get; set; }
        public Nullable<int> TRANSPORTADORAID { get; set; }
        public Nullable<decimal> FRETE_VALOR { get; set; }
        public Nullable<int> FRETE_TIPO { get; set; }
        public Nullable<decimal> SEGURO_VALOR { get; set; }
        public Nullable<decimal> OUTRASDESPESASACESSORIAS_VALOR { get; set; }
        public Nullable<bool> INCLUIRFRETESEGUROOUTRASDESPESAS_NO_IMPOSTO { get; set; }
        public string NATUREZADEOPERACAO { get; set; }
        public string NF_STATUS { get; set; }
        public string NF_ULTIMAMENSAGEM { get; set; }
        public string NF_RECIBO { get; set; }
        public string NF_CHAVEACESSO { get; set; }
        public Nullable<int> NF_NUMERO { get; set; }
        public string NF_PROTOCOLO { get; set; }
        public string NF_XML { get; set; }
        public int NF_TENTATIVA_TRANSMISSAO { get; set; }
        public string NF_CONTINGENCIA_XML { get; set; }
        public Nullable<System.DateTime> NF_CONTINGENCIA_DATA { get; set; }
        public decimal VALOR_TOTAL { get; set; }
        public string OBSERVACAO { get; set; }
        public int NF_TIPO { get; set; }
        public Nullable<System.DateTime> DATAFISCAL { get; set; }
        public Nullable<int> NF_FINALIDADE { get; set; }
        public string NF_CHAVEDEACESSOREFERENCIADAS { get; set; }
        public Nullable<decimal> PESO_BRUTO { get; set; }
        public Nullable<decimal> PESO_LIQUIDO { get; set; }
        public string ESPECIEVOLUMES { get; set; }
        public string MARCAVOLUMES { get; set; }
        public Nullable<decimal> NUMEROVOLUMES { get; set; }
        public Nullable<decimal> QUANTIDADEVOLUMES { get; set; }
        public Nullable<System.DateTime> DATA_ULTIMA_SINCRONIZACAO_PEDIDOWEB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notafiscal_cartacorrecao> notafiscal_cartacorrecao { get; set; }
        public virtual pessoa pessoa { get; set; }
        public virtual pessoa pessoa1 { get; set; }
        public virtual pessoa pessoa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notafiscalproduto> notafiscalproduto { get; set; }
    }
}
