//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class notafiscal_cartacorrecao
    {
        public int NotaFiscal_CartaCorrecaoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ISATIVO { get; set; }
        public string XML { get; set; }
        public string STATUS { get; set; }
        public string ULTIMAMENSAGEM { get; set; }
        public string CORRECAO { get; set; }
        public Nullable<int> NOTAFISCALID { get; set; }
    
        public virtual notafiscal notafiscal { get; set; }
    }
}
