//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class notafiscalproduto
    {
        public int NotaFiscalProdutoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ISATIVO { get; set; }
        public string GRADELEGENDA { get; set; }
        public int GRADENUMERO { get; set; }
        public Nullable<int> NOTAFISCALID { get; set; }
        public Nullable<int> PRODUTOID { get; set; }
        public string DESCRICAOPRODUTO { get; set; }
        public string REFERENCIA { get; set; }
        public decimal QUANTIDADE { get; set; }
        public decimal VALOR_UNITARIO { get; set; }
        public decimal DESCONTO_VALOR { get; set; }
        public decimal DESCONTO_PORCENTAGEM { get; set; }
        public decimal VALOR_TOTAL { get; set; }
        public decimal SUBTOTAL { get; set; }
        public string CFOP { get; set; }
        public string NCM { get; set; }
        public Nullable<int> ORIGEMMERCADORIA { get; set; }
        public Nullable<int> CSOSNCST { get; set; }
        public decimal ICMS_BASECALCULO { get; set; }
        public decimal ICMS_ALIQUOTA { get; set; }
        public decimal ICMS_VALOR { get; set; }
        public decimal ICMS_DIFAL { get; set; }
        public decimal ICMSST_BASECALCULO { get; set; }
        public decimal ICMSST_ALIQUOTA { get; set; }
        public decimal ICMSST_VALOR { get; set; }
        public decimal ICMSST_MVA { get; set; }
        public decimal IPI_ALIQUOTA { get; set; }
        public decimal IPI_VALOR { get; set; }
        public Nullable<int> IPI_CST { get; set; }
        public Nullable<int> PIS_CST { get; set; }
        public decimal PIS_ALIQUOTA { get; set; }
        public decimal PIS_VALOR { get; set; }
        public decimal PISST_ALIQUOTA { get; set; }
        public decimal PISST_VALOR { get; set; }
        public Nullable<int> COFINS_CST { get; set; }
        public decimal COFINS_ALIQUOTA { get; set; }
        public decimal COFINS_VALOR { get; set; }
        public decimal COFINSST_ALIQUOTA { get; set; }
        public decimal COFINSST_VALOR { get; set; }
        public decimal CREDITO_ALIQUOTA { get; set; }
        public decimal CREDITO_VALOR { get; set; }
        public string OBSERVACAO { get; set; }
        public decimal IPI_BASECALCULO { get; set; }
        public decimal PIS_BASECALCULO { get; set; }
        public decimal PISST_BASECALCULO { get; set; }
        public decimal COFINS_BASECALCULO { get; set; }
        public decimal COFINSST_BASECALCULO { get; set; }
        public string IPI_CODIGOENQUADRAMENTO { get; set; }
        public decimal FCPST_ALIQUOTA { get; set; }
        public decimal FCPST_VALOR { get; set; }
        public Nullable<bool> ZERARBASECALCULOICMSST { get; set; }
        public decimal FCP_ALIQUOTA { get; set; }
        public decimal FCP_VALOR { get; set; }
        public decimal REDUCAO_BC_ICMS { get; set; }
        public decimal REDUCAO_BC_ICMSST { get; set; }
        public string COD_BENEFICIO_FISCAL { get; set; }
        public Nullable<int> MODBC_ICMS { get; set; }
        public Nullable<int> MODBC_ICMSST { get; set; }
        public Nullable<decimal> ICMS_DIFERIMENTO_PORCENTAGEM { get; set; }
        public Nullable<decimal> ICMS_DIFERIMENTO_VALOR { get; set; }
        public Nullable<decimal> ICMS_DIFERIMENTO_SUBTRAIDO { get; set; }
        public string NUMEROPEDIDOCOMPRA { get; set; }
    
        public virtual notafiscal notafiscal { get; set; }
        public virtual produto produto { get; set; }
    }
}
