//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class notafiscal_pedido
    {
        public int NotaFiscal_PedidoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public int NOTAFISCALID { get; set; }
        public int PEDIDOID { get; set; }
        public decimal PEDIDOVALOR { get; set; }
        public System.DateTime PEDIDODATA { get; set; }
    }
}
