//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoproduto
    {
        public int PedidoProdutoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ISATIVO { get; set; }
        public string GRADELEGENDA { get; set; }
        public int GRADENUMERO { get; set; }
        public Nullable<int> PEDIDOID { get; set; }
        public Nullable<int> PRODUTOID { get; set; }
        public decimal QUANTIDADE { get; set; }
        public decimal VALOR_COMISSAO { get; set; }
        public decimal VALOR_COMPRA { get; set; }
        public decimal VALOR_CUSTO { get; set; }
        public decimal VALOR_DESCONTO { get; set; }
        public decimal VALOR_DESCONTO_PORCENTAGEM { get; set; }
        public decimal VALOR_VENDA_ATACADO { get; set; }
        public decimal VALOR_VENDA_ATACADO_MARGEMLUCRO { get; set; }
        public decimal VALOR_VENDA_VAREJO { get; set; }
        public decimal VALOR_VENDA_VAREJO_MARGEMLUCRO { get; set; }
        public Nullable<decimal> FATOR { get; set; }
        public string OBSERVACAO { get; set; }
        public decimal QUANTIDADE_DEVOLVIDA { get; set; }
        public decimal VALOR_ACRESCIMO { get; set; }
        public long HUB_ID { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual produto produto { get; set; }
    }
}
