//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.contaspagarreceberparcela = new HashSet<contaspagarreceberparcela>();
            this.pedidoproduto = new HashSet<pedidoproduto>();
        }
    
        public int PedidoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ISATIVO { get; set; }
        public Nullable<int> CLIENTEID { get; set; }
        public string CONDICAODEPAGAMENTORECEBIMENTO { get; set; }
        public string NFCE_STATUS { get; set; }
        public string NFCE_ULTIMAMENSAGEM { get; set; }
        public string NFCE_RECIBO { get; set; }
        public string NFCE_CHAVEACESSO { get; set; }
        public string NFCE_PROTOCOLO { get; set; }
        public string NFCE_XML { get; set; }
        public string OBSERVACAO { get; set; }
        public decimal VALOR_AVISTA { get; set; }
        public decimal VALOR_APRAZO { get; set; }
        public decimal VALOR_TOTAL { get; set; }
        public decimal VALOR_TOTAL_CUSTO { get; set; }
        public decimal VALOR_TOTAL_MARGEMLUCRO_PORCENTAGEM { get; set; }
        public decimal VALOR_TOTAL_MARGEMLUCRO_VALOR { get; set; }
        public Nullable<int> VENDEDORID { get; set; }
        public int STATUS { get; set; }
        public Nullable<int> NFCE_NUMERO { get; set; }
        public int SENHA { get; set; }
        public bool OBSERVACAO_INCLUIR_PEDIDO { get; set; }
        public bool OBSERVACAO_INCLUIR_NOTAFISCAL { get; set; }
        public int NFCE_TENTATIVA_TRANSMISSAO { get; set; }
        public string NFCE_CONTINGENCIA_XML { get; set; }
        public decimal FRETE { get; set; }
        public Nullable<int> REAJUSTAR_VALOR_DE_CUSTO_VENDA { get; set; }
        public Nullable<System.DateTime> DATA_ULTIMA_SINCRONIZACAO_PEDIDOWEB { get; set; }
        public Nullable<System.DateTime> NFCE_CONTINGENCIA_DATA { get; set; }
        public Nullable<System.DateTime> DATAFISCAL { get; set; }
        public string NUMERO_PREVENDA { get; set; }
        public decimal VALOR_TOTAL_COMISSAO { get; set; }
        public bool ISINDICARCONSUMIDORNFC { get; set; }
        public bool ISDELETADO { get; set; }
        public Nullable<int> ORIGINADO_DE { get; set; }
        public string STATUSDESCRICAO { get; set; }
        public decimal VALOR_FRETE { get; set; }
        public decimal VALOR_ACRESCIMO { get; set; }
        public long HUB_ID { get; set; }
        public bool PEDIDOAPI { get; set; }
        public int CondicionalPrimaryId { get; set; }
        public decimal VALOR_TOTAL_DEVOLUCAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contaspagarreceberparcela> contaspagarreceberparcela { get; set; }
        public virtual pessoa pessoa { get; set; }
        public virtual pessoa pessoa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidoproduto> pedidoproduto { get; set; }
    }
}
