//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pessoa()
        {
            this.contaspagarreceberparcela = new HashSet<contaspagarreceberparcela>();
            this.crediario = new HashSet<crediario>();
            this.crediario1 = new HashSet<crediario>();
            this.estoqueprodutomovimento = new HashSet<estoqueprodutomovimento>();
            this.notafiscal = new HashSet<notafiscal>();
            this.notafiscal1 = new HashSet<notafiscal>();
            this.notafiscal2 = new HashSet<notafiscal>();
            this.pedido = new HashSet<pedido>();
            this.pedido1 = new HashSet<pedido>();
            this.pessoa1 = new HashSet<pessoa>();
            this.pessoa11 = new HashSet<pessoa>();
            this.produto = new HashSet<produto>();
            this.segurancausuario = new HashSet<segurancausuario>();
            this.segurancausuario1 = new HashSet<segurancausuario>();
        }
    
        public int PessoaId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public bool ALERTAR { get; set; }
        public string APELIDO { get; set; }
        public bool ATIVO { get; set; }
        public string BAIRRO { get; set; }
        public string BAIRROCOBRANCA { get; set; }
        public string BAIRROENTREGA { get; set; }
        public bool BLOQUEADO { get; set; }
        public bool CADASTROCOMPLETO { get; set; }
        public string CELULAR { get; set; }
        public string CELULAROPERADORA { get; set; }
        public string CEP { get; set; }
        public string CEPCOBRANCA { get; set; }
        public string CEPENTREGA { get; set; }
        public string COMPLEMENTO { get; set; }
        public string COMPLEMENTOCOBRANCA { get; set; }
        public string COMPLEMENTOENTREGA { get; set; }
        public string CONJUGEBAIRRO { get; set; }
        public string CONJUGECARGO { get; set; }
        public string CONJUGECELULAR { get; set; }
        public string CONJUGECELULAROPERADORA { get; set; }
        public string CONJUGECEP { get; set; }
        public string CONJUGECOMPLEMENTO { get; set; }
        public string CONJUGECPF { get; set; }
        public Nullable<System.DateTime> CONJUGEDATACONTRATACAO { get; set; }
        public Nullable<System.DateTime> CONJUGEDATANASCIMENTO { get; set; }
        public string CONJUGEFAX { get; set; }
        public string CONJUGELOGRADOURO { get; set; }
        public string CONJUGEMUNICIPIO { get; set; }
        public string CONJUGENOME { get; set; }
        public string CONJUGENUMERO { get; set; }
        public string CONJUGEOBSERVACAO { get; set; }
        public string CONJUGERG { get; set; }
        public decimal CONJUGESALARIO { get; set; }
        public string CONJUGETELEFONE { get; set; }
        public string CONJUGETEMPOTRABALHO { get; set; }
        public int CONJUGEUFID { get; set; }
        public int CONJUGUEPAIS_ID { get; set; }
        public int CONSUMIDORFINAL { get; set; }
        public string CONTATO { get; set; }
        public int CONTRIBUINTE { get; set; }
        public string CPFCNPJ { get; set; }
        public int CRT { get; set; }
        public string CTPS { get; set; }
        public Nullable<System.DateTime> DATAADMISSAO { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public Nullable<System.DateTime> DATANASCIMENTO { get; set; }
        public Nullable<System.DateTime> DATAULTIMAALTERACAO { get; set; }
        public decimal DESCONTOMAXIMOPERMITIDO { get; set; }
        public string EMAIL { get; set; }
        public string EMAILFINANCEIRO { get; set; }
        public bool ENDERECOCOBRANCA_USARPRINCIPAL { get; set; }
        public bool ENDERECOENTREGA_USARPRINCIPAL { get; set; }
        public int ESTADOCIVIL { get; set; }
        public bool EXIBEOBSERVACAO { get; set; }
        public string FAMILIARESBAIRRO { get; set; }
        public string FAMILIARESCEP { get; set; }
        public string FAMILIARESCOMPLEMENTO { get; set; }
        public string FAMILIARESLOGRADOURO { get; set; }
        public string FAMILIARESMUNICIPIO { get; set; }
        public string FAMILIARESNOMEMAE { get; set; }
        public string FAMILIARESNOMEPAI { get; set; }
        public string FAMILIARESNUMERO { get; set; }
        public string FAMILIARESOBSERVACAO { get; set; }
        public int FAMILIARESPAIS_ID { get; set; }
        public string FAMILIARESTELEFONE { get; set; }
        public int FAMILIARESUFID { get; set; }
        public string FAX { get; set; }
        public string FISJUR { get; set; }
        public int FORMAPAGAMENTORECEBIMENTO { get; set; }
        public string FUNCAO { get; set; }
        public byte[] IMAGEM { get; set; }
        public string INSCRICAOMUNICIPAL { get; set; }
        public bool ISCASAPROPRIA { get; set; }
        public bool ISCLIENTE { get; set; }
        public bool ISFORNECEDOR { get; set; }
        public bool ISFUNCIONARIO { get; set; }
        public bool ISTRANSPORTADORA { get; set; }
        public bool ISVENDEDOR { get; set; }
        public decimal LIMITECREDITO { get; set; }
        public string LOGRADOURO { get; set; }
        public string LOGRADOUROCOBRANCA { get; set; }
        public string LOGRADOUROENTREGA { get; set; }
        public int METAPORPEDIDOFATURAMENTO { get; set; }
        public decimal METAVALORVENDA { get; set; }
        public string MOTIVOBLOQUEIO { get; set; }
        public string MUNICIPIO { get; set; }
        public string MUNICIPIOCOBRANCA { get; set; }
        public string MUNICIPIOENTREGA { get; set; }
        public string NATURALIDADE { get; set; }
        public string NOMEFANTASIA { get; set; }
        public string NOMERAZAOSOCIAL { get; set; }
        public string NUMERO { get; set; }
        public string NUMEROCOBRANCA { get; set; }
        public string NUMEROENTREGA { get; set; }
        public string OBSERVACAO { get; set; }
        public string ORGAOEXPEDIDOR { get; set; }
        public int PAIS_ID { get; set; }
        public int PAISCOBRANCA_ID { get; set; }
        public int PAISENTREGA_ID { get; set; }
        public string REFERENCIACOMERCIAL1CELULAR { get; set; }
        public string REFERENCIACOMERCIAL1CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL1NOME { get; set; }
        public string REFERENCIACOMERCIAL1TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL2CELULAR { get; set; }
        public string REFERENCIACOMERCIAL2CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL2NOME { get; set; }
        public string REFERENCIACOMERCIAL2TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL3CELULAR { get; set; }
        public string REFERENCIACOMERCIAL3CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL3NOME { get; set; }
        public string REFERENCIACOMERCIAL3TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL4CELULAR { get; set; }
        public string REFERENCIACOMERCIAL4CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL4NOME { get; set; }
        public string REFERENCIACOMERCIAL4TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL5CELULAR { get; set; }
        public string REFERENCIACOMERCIAL5CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL5NOME { get; set; }
        public string REFERENCIACOMERCIAL5TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL6CELULAR { get; set; }
        public string REFERENCIACOMERCIAL6CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL6NOME { get; set; }
        public string REFERENCIACOMERCIAL6TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL7CELULAR { get; set; }
        public string REFERENCIACOMERCIAL7CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL7NOME { get; set; }
        public string REFERENCIACOMERCIAL7TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL8CELULAR { get; set; }
        public string REFERENCIACOMERCIAL8CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL8NOME { get; set; }
        public string REFERENCIACOMERCIAL8TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL9CELULAR { get; set; }
        public string REFERENCIACOMERCIAL9CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL9NOME { get; set; }
        public string REFERENCIACOMERCIAL9TELEFONE { get; set; }
        public string REFERENCIACOMERCIAL10CELULAR { get; set; }
        public string REFERENCIACOMERCIAL10CELULAROPERADORA { get; set; }
        public string REFERENCIACOMERCIAL10NOME { get; set; }
        public string REFERENCIACOMERCIAL10TELEFONE { get; set; }
        public string RGIE { get; set; }
        public decimal SALARIO { get; set; }
        public string SEXO { get; set; }
        public int SITUACAOCIVIL { get; set; }
        public string TAXAENTREGA { get; set; }
        public string TELEFONE { get; set; }
        public bool TELEMARKETINGNAOLIGAR { get; set; }
        public int TELEMARKETINGRECORRENCIA { get; set; }
        public int TIPO { get; set; }
        public int TIPOEMAILPARAENVIARNFE { get; set; }
        public int TIPOPAGAMENTORECEBIMENTO { get; set; }
        public string TRABALHOBAIRRO { get; set; }
        public string TRABALHOCARGO { get; set; }
        public string TRABALHOCELULAR { get; set; }
        public string TRABALHOCELULAROPERADORA { get; set; }
        public string TRABALHOCEP { get; set; }
        public string TRABALHOCOMPLEMENTO { get; set; }
        public Nullable<System.DateTime> TRABALHODATACONTRATACAO { get; set; }
        public string TRABALHOFAX { get; set; }
        public string TRABALHOLOCAL { get; set; }
        public string TRABALHOLOGRADOURO { get; set; }
        public string TRABALHOMUNICIPIO { get; set; }
        public string TRABALHONUMERO { get; set; }
        public string TRABALHOOBSERVACAO { get; set; }
        public int TRABALHOPAIS_ID { get; set; }
        public decimal TRABALHOSALARIO { get; set; }
        public string TRABALHOTELEFONE { get; set; }
        public string TRABALHOTEMPOTRABALHO { get; set; }
        public int TRABALHOUFID { get; set; }
        public Nullable<int> TRANSPORTADORAID { get; set; }
        public int UF { get; set; }
        public int UFCOBRANCA { get; set; }
        public int UFENTREGA { get; set; }
        public Nullable<int> VENDEDORID { get; set; }
        public string CADASTROUSUARIO { get; set; }
        public long WEB_KEY { get; set; }
        public Nullable<int> MOTIVOAPOSENTADORIA { get; set; }
        public string NUMEROBENEFICIOAPOSENTADORIA { get; set; }
        public Nullable<System.DateTime> SINCRONIZADO_EM { get; set; }
        public decimal VALORBENEFICIOAPOSENTADORIA { get; set; }
        public Nullable<System.DateTime> FAMILIARESDATANASCIMENTOFILHO01 { get; set; }
        public Nullable<System.DateTime> FAMILIARESDATANASCIMENTOFILHO02 { get; set; }
        public Nullable<System.DateTime> FAMILIARESDATANASCIMENTOFILHO03 { get; set; }
        public Nullable<System.DateTime> FAMILIARESDATANASCIMENTOFILHO04 { get; set; }
        public string FAMILIARESNOMEFILHO01 { get; set; }
        public string FAMILIARESNOMEFILHO02 { get; set; }
        public string FAMILIARESNOMEFILHO03 { get; set; }
        public string FAMILIARESNOMEFILHO04 { get; set; }
        public bool ISISCRICAOESTADUAL { get; set; }
        public long HUB_ID { get; set; }
        public bool ISPRODUTORRURAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contaspagarreceberparcela> contaspagarreceberparcela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crediario> crediario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crediario> crediario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estoqueprodutomovimento> estoqueprodutomovimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notafiscal> notafiscal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notafiscal> notafiscal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notafiscal> notafiscal2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pessoa> pessoa1 { get; set; }
        public virtual pessoa pessoa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pessoa> pessoa11 { get; set; }
        public virtual pessoa pessoa3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produto> produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<segurancausuario> segurancausuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<segurancausuario> segurancausuario1 { get; set; }
    }
}
