//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtokitcomposicao
    {
        public int KITCOMPOSICAO { get; set; }
        public int PRODUTOID { get; set; }
        public int PRODUTOKIT { get; set; }
        public decimal QUANTIDADE { get; set; }
        public decimal VALOR { get; set; }
        public decimal CUSTO { get; set; }
    }
}
