//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.balancoproduto = new HashSet<balancoproduto>();
            this.estoqueproduto1 = new HashSet<estoqueproduto>();
            this.estoqueprodutomovimento = new HashSet<estoqueprodutomovimento>();
            this.imagemproduto = new HashSet<imagemproduto>();
            this.notafiscalproduto = new HashSet<notafiscalproduto>();
            this.pedidoproduto = new HashSet<pedidoproduto>();
            this.transferenciaestoqueproduto = new HashSet<transferenciaestoqueproduto>();
        }
    
        public int ProdutoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public bool ISATIVO { get; set; }
        public string CFOP { get; set; }
        public Nullable<int> CLASSIFICACAOFISCALID { get; set; }
        public Nullable<int> COLECAOID { get; set; }
        public string COR { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public string DESCRICAO { get; set; }
        public string DESCRICAORESUMIDA { get; set; }
        public Nullable<int> DEPARTAMENTOID { get; set; }
        public decimal ESTOQUEMINIMO { get; set; }
        public Nullable<int> FABRICANTEID { get; set; }
        public Nullable<int> FORNECEDORID { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<int> GRUPOID { get; set; }
        public byte[] IMAGEM { get; set; }
        public Nullable<int> MARCAID { get; set; }
        public string NCM { get; set; }
        public int TIPOMERCADORIA { get; set; }
        public Nullable<int> UNIDADEID { get; set; }
        public decimal VALOR_COMISSAO { get; set; }
        public decimal VALOR_COMPRA { get; set; }
        public decimal VALOR_CUSTO { get; set; }
        public decimal VALOR_VENDA_ATACADO { get; set; }
        public decimal VALOR_VENDA_ATACADO_MARGEMLUCRO { get; set; }
        public decimal VALOR_VENDA_VAREJO { get; set; }
        public decimal VALOR_VENDA_VAREJO_MARGEMLUCRO { get; set; }
        public Nullable<int> SubGrupo_SubGrupoId { get; set; }
        public bool DESATIVARAUTOINSERCAO { get; set; }
        public string UNIDADE_BALANCA { get; set; }
        public string CSOSNCST { get; set; }
        public string CEST { get; set; }
        public string COFINSCST { get; set; }
        public string PISCST { get; set; }
        public decimal VALOR_CUSTO_OPERACIONAL { get; set; }
        public decimal DESCONTO_VALOR { get; set; }
        public int DESCONTO_QUANDO { get; set; }
        public decimal DESCONTO_QUANTIDADE { get; set; }
        public Nullable<int> VALIDADE { get; set; }
        public Nullable<bool> EXPORTAR_BALANCA { get; set; }
        public string REFERENCIAPRODUTO { get; set; }
        public string CODIGOCOMDESCRICAOANP { get; set; }
        public string CADASTROUSUARIO { get; set; }
        public long WEB_KEY { get; set; }
        public Nullable<System.DateTime> SINCRONIZADO_EM { get; set; }
        public string SKU { get; set; }
        public bool ISDELETADO { get; set; }
        public bool ISWEBSEND { get; set; }
        public string IMAGEM_MD5 { get; set; }
        public byte[] IMAGEM_REDUZIDA { get; set; }
        public Nullable<int> PRODUTOID_UNIFICADO { get; set; }
        public decimal DESCONTOMAXIMOPERMITIDO { get; set; }
        public string REFERENCIAPADRAO { get; set; }
        public bool UTILIZARKITCOMPOSICAO { get; set; }
        public bool ADICIONARITENSINDIVIDUALMENTE { get; set; }
        public Nullable<bool> UTILIZALEITURAPESOBALANCA { get; set; }
        public decimal ESTOQUEPRODUTO { get; set; }
        public Nullable<bool> ISISENTOACRESCIMO { get; set; }
        public Nullable<int> PRODUTO_FRAGMENTACAO { get; set; }
        public Nullable<decimal> QUANTIDADE_FRAGMENTACAO { get; set; }
        public long HUB_ID { get; set; }
        public decimal VALOR_VENDA_SITE { get; set; }
        public decimal VALOR_VENDA_SITE_MARGEMLUCRO { get; set; }
        public string DESCRICAOPRODUTO { get; set; }
        public string PESOPRODUTO { get; set; }
        public string ALTURAPRODUTO { get; set; }
        public string LARGURAPRODUTO { get; set; }
        public string COMPRIMENTOPRODUTO { get; set; }
        public int EXIBIRSELODESTAQUE { get; set; }
        public int EXIBIRSELOLANÇAMENTO { get; set; }
        public int EXIBIRSELOADICIONAL { get; set; }
        public bool REAJUSTAR_VALOR_VENDA { get; set; }
        public decimal PRECO_PROMOCAO { get; set; }
        public Nullable<System.DateTime> PERIODO_PROMOCAO_DE { get; set; }
        public Nullable<System.DateTime> PERIODO_PROMOCAO_ATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<balancoproduto> balancoproduto { get; set; }
        public virtual classificacaofiscal classificacaofiscal { get; set; }
        public virtual colecao colecao { get; set; }
        public virtual departamento departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estoqueproduto> estoqueproduto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estoqueprodutomovimento> estoqueprodutomovimento { get; set; }
        public virtual fabricante fabricante { get; set; }
        public virtual grade grade { get; set; }
        public virtual grupo grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imagemproduto> imagemproduto { get; set; }
        public virtual marca marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notafiscalproduto> notafiscalproduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidoproduto> pedidoproduto { get; set; }
        public virtual pessoa pessoa { get; set; }
        public virtual subgrupo subgrupo { get; set; }
        public virtual unidade unidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transferenciaestoqueproduto> transferenciaestoqueproduto { get; set; }
    }
}
