//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class referencia
    {
        public int ReferenciaId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ISATIVO { get; set; }
        public string REFERENCIA1 { get; set; }
        public bool ISPADRAO { get; set; }
        public int PRODUTOID { get; set; }
        public string CADASTROUSUARIO { get; set; }
        public long WEB_KEY { get; set; }
    }
}
