//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class regracomissao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public regracomissao()
        {
            this.regracomissaocolecao = new HashSet<regracomissaocolecao>();
            this.regracomissaofornecedor = new HashSet<regracomissaofornecedor>();
            this.regracomissaogrupo = new HashSet<regracomissaogrupo>();
            this.regracomissaomarca = new HashSet<regracomissaomarca>();
            this.regracomissaoproduto = new HashSet<regracomissaoproduto>();
        }
    
        public int RegraComissaoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATA_INICIO { get; set; }
        public Nullable<System.DateTime> DATA_FIM { get; set; }
        public bool ATIVO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public string TIPO_COMISSAO { get; set; }
        public decimal COMISSAO_MOEDA { get; set; }
        public decimal COMISSAO_PORCENTAGEM { get; set; }
        public string NOME_REGRA { get; set; }
        public int PRIORIDADE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regracomissaocolecao> regracomissaocolecao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regracomissaofornecedor> regracomissaofornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regracomissaogrupo> regracomissaogrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regracomissaomarca> regracomissaomarca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regracomissaoproduto> regracomissaoproduto { get; set; }
    }
}
