//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class segurancaperfilpermissao
    {
        public int SegurancaPerfilPermissaoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public string PERMISSAO { get; set; }
        public Nullable<int> PERFILID { get; set; }
    
        public virtual segurancaperfil segurancaperfil { get; set; }
    }
}
