//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class segurancausuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public segurancausuario()
        {
            this.caixa = new HashSet<caixa>();
        }
    
        public int SegurancaUsuarioId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public Nullable<int> CLIENTEID { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public int EMAILCONFIGURACAO { get; set; }
        public Nullable<int> FUNCIONARIOID { get; set; }
        public bool ISATIVO { get; set; }
        public Nullable<int> PERFILID { get; set; }
        public string SENHA { get; set; }
        public string USUARIO { get; set; }
        public bool ISPESQUISASATIFACAO { get; set; }
        public bool UTILIZADESCONTOMAXIMOPERMITIDO { get; set; }
        public decimal DESCONTOMAXIMOPERMITIDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caixa> caixa { get; set; }
        public virtual pessoa pessoa { get; set; }
        public virtual pessoa pessoa1 { get; set; }
        public virtual segurancaperfil segurancaperfil { get; set; }
    }
}
