//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class sincronizacao
    {
        public int SincronizacaoId { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public bool ATLCOLECAO { get; set; }
        public bool ATLDEPARTAMENTO { get; set; }
        public bool ATLFABRICANTE { get; set; }
        public bool ATLGRADE { get; set; }
        public bool ATLGRUPO { get; set; }
        public bool ATLMARCA { get; set; }
        public bool ATLPESSOA { get; set; }
        public bool ATLPRODUTO { get; set; }
        public bool ATLSETOR { get; set; }
        public bool ATLUNIDADE { get; set; }
        public Nullable<System.DateTime> COLECAO_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> DEPARTAMENTO_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> FABRICANTE_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> GRUPO_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> MARCA_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> SETOR_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> UNIDADE_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> GRADE_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> PESSOA_RECEBIDO_EM { get; set; }
        public Nullable<System.DateTime> PRODUTO_RECEBIDO_EM { get; set; }
        public bool ATLTRANSFERENCIA { get; set; }
        public Nullable<System.DateTime> TRANSFERENCIA_RECEBIDO_EM { get; set; }
    }
}
