//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferenciaestoqueproduto
    {
        public int TransferenciaEstoqueProdutoId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public decimal QUANTIDADE_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_01_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_02_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_03_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_04_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_05_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_06_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_07_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_08_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_09_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_10_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_11_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_12_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_13_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_14_ENVIADA { get; set; }
        public decimal GRADE_QUANTIDADE_15_ENVIADA { get; set; }
        public decimal QUANTIDADE_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_01_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_02_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_03_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_04_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_05_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_06_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_07_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_08_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_09_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_10_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_11_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_12_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_13_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_14_RECEBIDA { get; set; }
        public decimal GRADE_QUANTIDADE_15_RECEBIDA { get; set; }
        public int SITUACAO { get; set; }
        public int PRODUTOID { get; set; }
        public int TRANSFERENCIAESTOQUEID { get; set; }
        public long WEB_KEY { get; set; }
        public Nullable<System.DateTime> SINCRONIZADO_EM { get; set; }
    
        public virtual produto produto { get; set; }
        public virtual transferenciaestoque transferenciaestoque { get; set; }
    }
}
