//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LILO.Destino
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferenciaestoque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transferenciaestoque()
        {
            this.transferenciaestoqueproduto = new HashSet<transferenciaestoqueproduto>();
        }
    
        public int TransferenciaEstoqueId { get; set; }
        public System.DateTime ALTERACAODATA { get; set; }
        public string ALTERACAOUSUARIO { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public string DESCRICAO { get; set; }
        public int DESTINO { get; set; }
        public string OBSERVACAO { get; set; }
        public int ORIGEM { get; set; }
        public int STATUS { get; set; }
        public long WEB_KEY { get; set; }
        public Nullable<System.DateTime> SINCRONIZADO_EM { get; set; }
        public bool ISDELETADO { get; set; }
        public bool ISPENDENTE { get; set; }
        public long VINCULO_WEBKEY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transferenciaestoqueproduto> transferenciaestoqueproduto { get; set; }
    }
}
